import { randomUUID } from 'node:crypto';
import { expect, test, type APIResponse, type Locator, type Page } from '@playwright/test';
import pg, { type Pool as PgPool } from 'pg';
import { readE2eEnvironment } from '../../scripts/e2e-database.mjs';
import { assertAuthenticatedAdmin } from './support/auth';

const { Pool } = pg;
let database: PgPool;

test.beforeAll(() => {
  const { databaseUrl } = readE2eEnvironment();
  database = new Pool({ connectionString: databaseUrl, ssl: false });
});

test.afterAll(async () => {
  if (database) await (database as PgPool & { end: () => Promise<void> }).end();
});

test.beforeEach(async ({ request }) => {
  await assertAuthenticatedAdmin(request);
});

async function requireOk(response: APIResponse, description: string) {
  if (!response.ok()) {
    throw new Error(`${description}: HTTP ${response.status()}: ${await response.text()}`);
  }
}

async function selectRenderedText(locator: Locator, length?: number) {
  return locator.evaluate((element, selectedLength) => {
    const selection = window.getSelection();
    if (!selection) throw new Error('Browser text selection is unavailable.');
    const range = document.createRange();
    if (selectedLength === undefined) {
      range.selectNodeContents(element);
    } else {
      const walker = document.createTreeWalker(element, NodeFilter.SHOW_TEXT);
      let text = walker.nextNode();
      while (text && !text.textContent?.trim()) text = walker.nextNode();
      if (!text || (text.textContent?.length ?? 0) < selectedLength) {
        throw new Error('The displayed public code is not selectable text.');
      }
      range.setStart(text, 0);
      range.setEnd(text, selectedLength);
    }
    selection.removeAllRanges();
    selection.addRange(range);
    return selection.toString();
  }, length);
}

async function seedClipboard(page: Page) {
  const sentinel = `not-copied-${randomUUID()}`;
  await page.evaluate((value) => navigator.clipboard.writeText(value), sentinel);
}

async function expectClipboard(page: Page, value: string) {
  await expect.poll(() => page.evaluate(() => navigator.clipboard.readText())).toBe(value);
}

for (const kind of ['order', 'quote'] as const) {
  test(`${kind} list prioritizes its internal number and copies the complete public code`, async ({ page, request }, testInfo) => {
    test.setTimeout(60_000);
    await page.setViewportSize({ width: 1049, height: 1000 });
    let id: number | null = null;
    const createPath = kind === 'order' ? '/api/admin/orders' : '/api/admin/quote-requests';

    try {
      const create = await request.post(createPath, kind === 'quote' ? { data: { mode: 'draft' } } : undefined);
      await requireOk(create, `Create ${kind} copy fixture`);
      const created = await create.json() as { orderId?: unknown; quoteRequestId?: unknown };
      id = Number(kind === 'order' ? created.orderId : created.quoteRequestId);
      expect(Number.isSafeInteger(id) && id > 0).toBe(true);

      // Read the actual immutable identifier generated by the normal API, never assign a fake code.
      const record = kind === 'order'
        ? await database.query<{ internal_number: string; public_code_base: string }>(
          'select order_number as internal_number, public_code_base from orders where id = $1', [id])
        : await database.query<{ internal_number: string; public_code_base: string }>(
          'select request_number as internal_number, public_code_base from quote_requests where id = $1', [id]);
      expect(record.rows).toHaveLength(1);
      const { internal_number: internalNumber, public_code_base: base } = record.rows[0]!;
      expect(base).toMatch(/^[23456789ABCDEFGHJKMNPQRSTVWXYZ]{16}$/u);
      const fullCode = `${kind === 'order' ? 'N' : 'PV'}-${base.match(/.{4}/gu)!.join('-')}`;
      const shortCode = `${fullCode.slice(0, 6)}…${fullCode.slice(-4)}`;
      const primaryNumber = kind === 'order'
        ? internalNumber
        : `#${Number(internalNumber.match(/(\d+)$/u)![1])}`;
      const detailPath = kind === 'order' ? `/admin/orders/${id}` : `/admin/orders/quotes/${id}`;
      const listPath = `/admin/orders?${kind === 'quote' ? 'view=quotes&' : ''}q=${encodeURIComponent(fullCode)}`;
      await page.goto(listPath);
      await page.bringToFront();

      const primary = page.locator(`a[href="${detailPath}"]`).first();
      const code = page.getByTestId(`${kind}-public-code-${id}`);
      await expect(primary).toHaveText(primaryNumber);
      await expect(primary).toHaveAccessibleName(`Odpri ${kind === 'order' ? 'naročilo' : 'povpraševanje'} ${primaryNumber}`);
      await expect(code).toHaveText(shortCode);
      await expect(code).toHaveAttribute('title', fullCode);
      await expect(code).toHaveAccessibleName(new RegExp(`^Kopiraj celotno kodo .+: ${fullCode}$`, 'u'));
      expect(await code.textContent()).not.toContain(fullCode);
      const primaryBox = await primary.boundingBox();
      const codeBox = await code.boundingBox();
      expect(primaryBox).not.toBeNull();
      expect(codeBox).not.toBeNull();
      expect(codeBox!.y).toBeGreaterThanOrEqual(primaryBox!.y + primaryBox!.height - 1);
      const primaryStyle = await primary.evaluate((element) => {
        const style = getComputedStyle(element);
        return { size: Number.parseFloat(style.fontSize), weight: Number.parseInt(style.fontWeight, 10) };
      });
      const codeStyle = await code.evaluate((element) => {
        const style = getComputedStyle(element);
        return { size: Number.parseFloat(style.fontSize), weight: Number.parseInt(style.fontWeight, 10), select: style.userSelect };
      });
      expect(primaryStyle.size).toBeGreaterThan(codeStyle.size);
      expect(primaryStyle.weight).toBeGreaterThanOrEqual(codeStyle.weight);
      expect(codeStyle.select).not.toBe('none');

      await testInfo.attach(`${kind}-identifier-cell-1049`, {
        body: await code.locator('xpath=ancestor::td').screenshot({ path: testInfo.outputPath(`${kind}-identifier-cell-1049.png`) }),
        contentType: 'image/png'
      });

      await page.context().grantPermissions(['clipboard-read', 'clipboard-write'], { origin: new URL(page.url()).origin });
      const isSameFilteredList = (url: URL) => url.pathname === '/admin/orders'
        && url.searchParams.get('q') === fullCode
        && (url.searchParams.get('view') === 'quotes') === (kind === 'quote');
      const row = code.locator('xpath=ancestor::tr');
      const selection = row.getByRole('checkbox');
      await expect(selection).not.toBeChecked();
      await seedClipboard(page);
      await code.click();
      await expectClipboard(page, fullCode);
      await expect(page).toHaveURL(isSameFilteredList);
      await expect(selection).not.toBeChecked();

      for (const key of ['Enter', 'Space']) {
        await page.evaluate(() => window.getSelection()?.removeAllRanges());
        await code.focus();
        await seedClipboard(page);
        await page.keyboard.press(key);
        await expectClipboard(page, fullCode);
        await expect(page).toHaveURL(isSameFilteredList);
        await expect(selection).not.toBeChecked();
      }

      // Drag the actual rendered text, not a synthetic range. Reset the clipboard after
      // mouseup so a click handler cannot accidentally satisfy the subsequent copy check.
      const dragBox = await code.boundingBox();
      expect(dragBox).not.toBeNull();
      await page.mouse.move(dragBox!.x + 0.5, dragBox!.y + dragBox!.height / 2);
      await page.mouse.down();
      await page.mouse.move(dragBox!.x + dragBox!.width - 0.5, dragBox!.y + dragBox!.height / 2, { steps: 12 });
      await page.mouse.up();
      expect(await page.evaluate(() => window.getSelection()?.toString().trim())).toBe(shortCode);
      await seedClipboard(page);
      await page.keyboard.press('Control+C');
      await expectClipboard(page, fullCode);
      await expect(page).toHaveURL(isSameFilteredList);
      await expect(selection).not.toBeChecked();

      // A real browser selection and Ctrl+C exercises the document copy event and OS clipboard.
      // Focus intentionally stays outside the code: mouse/context-menu selection need not focus the button.
      await primary.focus();
      await seedClipboard(page);
      expect(await selectRenderedText(code)).toBe(shortCode);
      await page.keyboard.press('Control+C');
      await expectClipboard(page, fullCode);
      await expect(page).toHaveURL(isSameFilteredList);

      // Only selecting the complete displayed short code should expand it on the clipboard.
      await seedClipboard(page);
      const partialCode = await selectRenderedText(code, 3);
      expect(partialCode).toBe(shortCode.slice(0, 3));
      await page.keyboard.press('Control+C');
      await expectClipboard(page, partialCode);

      await seedClipboard(page);
      expect(await selectRenderedText(primary)).toBe(primaryNumber);
      await page.keyboard.press('Control+C');
      await expectClipboard(page, primaryNumber);

      // Editable controls must retain their native copy behavior even when the document
      // still contains a complete public-code selection from an earlier interaction.
      const textareaText = `Copy this textarea text ${randomUUID()}`;
      await page.evaluate((value) => {
        const textarea = document.createElement('textarea');
        textarea.dataset.testid = 'copy-regression-textarea';
        textarea.value = value;
        textarea.style.cssText = 'position:fixed;bottom:0;right:0;width:320px;height:50px;z-index:99999;';
        document.body.append(textarea);
        textarea.focus();
        textarea.select();
      }, textareaText);
      try {
        expect(await selectRenderedText(code)).toBe(shortCode);
        await expect(page.getByTestId('copy-regression-textarea')).toBeFocused();
        // Restoring a DOM range programmatically changes Chrome's native copy source.
        // Assert our listener leaves that stale-range event alone, then exercise the
        // textarea's normal native selection/copy path with the real clipboard.
        const untouchedCopy = await page.getByTestId('copy-regression-textarea').evaluate((element, value) => {
          const clipboardData = new DataTransfer();
          clipboardData.setData('text/plain', value);
          const event = new ClipboardEvent('copy', { bubbles: true, cancelable: true, clipboardData });
          element.dispatchEvent(event);
          return { prevented: event.defaultPrevented, text: clipboardData.getData('text/plain') };
        }, textareaText);
        expect(untouchedCopy).toEqual({ prevented: false, text: textareaText });
        await page.getByTestId('copy-regression-textarea').evaluate((element) => (element as HTMLTextAreaElement).select());
        await seedClipboard(page);
        await page.keyboard.press('Control+C');
        await expectClipboard(page, textareaText);
      } finally {
        await page.getByTestId('copy-regression-textarea').evaluate((element) => element.remove());
      }
      await page.evaluate(() => window.getSelection()?.removeAllRanges());
      await primary.click();
      await expect(page).toHaveURL(new RegExp(`${detailPath}$`, 'u'));
      await expect(page.getByTestId(kind === 'order' ? 'admin-order-detail-header' : 'admin-quote-detail')).toBeVisible();
    } finally {
      if (id !== null && Number.isSafeInteger(id) && id > 0) {
        const cleanup = await request.delete(`${createPath}/${id}`, kind === 'quote'
          ? { data: { reason: 'E2E public-code clipboard regression cleanup.' } }
          : undefined);
        await requireOk(cleanup, `Remove ${kind} copy fixture ${id}`);
      }
    }
  });
}
