import { formatEuro } from '@/shared/domain/formatting';
import type { CatalogVariantContentOverride } from '@/shared/domain/catalog/catalogAdminTypes';
import { formatDecimalForDisplay } from './decimalFormat';

type SeedItemTuple = [
  id: string,
  name: string,
  description: string,
  category: string,
  categoryId: string | null,
  subcategoryId: string | null,
  price: number,
  sku: string,
  images: string[],
  discountPct: number,
  displayOrder: number | null
];

export type Variant = {
  id: string;
  label: string;
  width: number | null;
  length: number | null;
  thickness: number | null;
  errorTolerance?: string | null;
  weight?: number | null;
  minOrder?: number;
  badge?: string | null;
  position?: number;
  skuAutoGenerated?: boolean;
  sku: string;
  price: number;
  costNet?: number | null;
  contentOverride?: CatalogVariantContentOverride | null;
  discountPct: number;
  stock: number;
  active: boolean;
  sort: number;
  imageOverride?: string | null;
  imageAssignments?: number[];
  optionValueIds?: number[];
  optionSelections?: Record<string, string>;
};

export type ProductOptionValueDraft = {
  id: string;
  value: string;
  slug: string;
  swatch?: string | null;
  position: number;
};

export type ProductOptionAxisDraft = {
  id: string;
  name: string;
  slug: string;
  position: number;
  values: ProductOptionValueDraft[];
};

export type ProductFamily = {
  id: string;
  name: string;
  description: string;
  category: string;
  categoryId: string | null;
  subcategoryId: string | null;
  images: string[];
  promoBadge: string;
  defaultDiscountPct: number;
  active: boolean;
  sort: number;
  notes: string;
  slug: string;
  defaultVariantId: string | null;
  optionAxes: ProductOptionAxisDraft[];
  variants: Variant[];
};

const parseDimensionTriplet = (input: string): { width: number | null; length: number | null; thickness: number | null } => {
  const normalized = input.replace(/,/g, '.').toLowerCase();
  const matches = normalized.match(/(\d+(?:\.\d+)?)/g);
  if (!matches || matches.length < 3) {
    return { width: null, length: null, thickness: null };
  }
  return {
    length: Number(matches[0]),
    width: Number(matches[1]),
    thickness: Number(matches[2])
  };
};

export const toSlug = (value: string) =>
  value
    .toLowerCase()
    .normalize('NFD')
    .replace(/\p{Diacritic}/gu, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');

export const computeSalePrice = (price: number, discountPct: number) =>
  Number((price * (1 - Math.max(0, Math.min(100, discountPct)) / 100)).toFixed(2));

export const formatCurrency = formatEuro;

type VariantNameSource = Pick<Variant, 'width' | 'length' | 'thickness'> & {
  label?: string | null;
  weight?: number | null;
};

const isFiniteMeasurement = (value: number | null | undefined): value is number =>
  typeof value === 'number' && Number.isFinite(value);

const buildVariantMeasurementName = (
  variant: VariantNameSource,
  fallbackLabel = 'Osnovna različica'
) => {
  const dimensions = [variant.thickness, variant.length, variant.width]
    .filter(isFiniteMeasurement)
    .map(formatDecimalForDisplay);

  if (dimensions.length > 0) {
    return `${dimensions.join(' × ')} mm`;
  }

  if (isFiniteMeasurement(variant.weight)) {
    return `${formatDecimalForDisplay(variant.weight)} g`;
  }

  const label = variant.label?.trim();
  return label || fallbackLabel;
};

export const buildPersistedVariantName = (
  variant: VariantNameSource,
  options: { baseName: string; variantCount: number; index?: number }
) => {
  const baseName = options.baseName.trim();
  if (options.variantCount === 1 && baseName) return baseName;
  return buildVariantMeasurementName(variant, `Različica ${(options.index ?? 0) + 1}`);
};

export const createVariant = (overrides: Partial<Variant> = {}): Variant => ({
  id: `var-${Math.random().toString(36).slice(2, 10)}`,
  label: 'Nova različica',
  width: null,
  length: null,
  thickness: null,
  errorTolerance: null,
  weight: null,
  minOrder: 1,
  sku: '',
  skuAutoGenerated: true,
  price: 0,
  costNet: null,
  contentOverride: null,
  discountPct: 0,
  stock: 0,
  active: true,
  sort: 1,
  imageOverride: null,
  imageAssignments: [],
  optionValueIds: [],
  optionSelections: {},
  ...overrides
});

export type DuplicateSelectedVariantResult = {
  variants: Variant[];
  duplicatedVariant: Variant | null;
};

const buildUniqueDuplicateSku = (source: Variant, variants: readonly Variant[]) => {
  const usedSkus = new Set(
    variants
      .map((variant) => variant.sku.trim().toLocaleLowerCase('sl'))
      .filter(Boolean)
  );
  const sourceSku = source.sku.trim();
  const fallbackSku = toSlug(source.label).toUpperCase() || 'RAZLICICA';
  const sourceBase = sourceSku || fallbackSku;
  const existingCopyMatch = sourceBase.match(/^(.*-KOPIJA)(?:-\d+)?$/i);
  const copyBase = existingCopyMatch?.[1] ?? `${sourceBase}-KOPIJA`;

  let candidate = copyBase;
  let copyNumber = 2;
  while (usedSkus.has(candidate.toLocaleLowerCase('sl'))) {
    candidate = `${copyBase}-${copyNumber}`;
    copyNumber += 1;
  }
  return candidate;
};

const buildUniqueVariantClientId = (
  variants: readonly Variant[],
  createId: () => string
) => {
  const usedIds = new Set(variants.map((variant) => variant.id));
  const generatedId = createId().trim();
  const nonNumericBase = !generatedId || /^\d+$/.test(generatedId)
    ? `var-${generatedId || 'copy'}`
    : generatedId;

  let candidate = nonNumericBase;
  let copyNumber = 2;
  while (usedIds.has(candidate)) {
    candidate = `${nonNumericBase}-${copyNumber}`;
    copyNumber += 1;
  }
  return candidate;
};

export const duplicateSelectedVariant = (
  variants: Variant[],
  selectedVariantIds: readonly string[],
  createId: () => string = () => `var-${Math.random().toString(36).slice(2, 10)}`
): DuplicateSelectedVariantResult => {
  if (selectedVariantIds.length !== 1) {
    return { variants, duplicatedVariant: null };
  }

  const sourceIndex = variants.findIndex((variant) => variant.id === selectedVariantIds[0]);
  if (sourceIndex < 0) {
    return { variants, duplicatedVariant: null };
  }

  const source = variants[sourceIndex];
  const duplicatedVariant: Variant = {
    ...source,
    id: buildUniqueVariantClientId(variants, createId),
    sku: buildUniqueDuplicateSku(source, variants),
    skuAutoGenerated: false,
    active: false,
    sort: variants.length + 1,
    contentOverride: source.contentOverride
      ? {
          ...source.contentOverride,
          specifications: source.contentOverride.specifications
            ? { ...source.contentOverride.specifications }
            : undefined,
          attributes: source.contentOverride.attributes
            ? { ...source.contentOverride.attributes }
            : undefined,
          includedItems: source.contentOverride.includedItems
            ? [...source.contentOverride.includedItems]
            : undefined,
          documentIds: source.contentOverride.documentIds
            ? [...source.contentOverride.documentIds]
            : undefined
        }
      : null,
    imageAssignments: [...(source.imageAssignments ?? [])],
    optionValueIds: [...(source.optionValueIds ?? [])],
    optionSelections: { ...(source.optionSelections ?? {}) }
  };
  const orderedVariants = [...variants, duplicatedVariant].map((variant, index) => ({
    ...variant,
    sort: index + 1
  }));

  return {
    variants: orderedVariants,
    duplicatedVariant: orderedVariants.at(-1) ?? null
  };
};

export type VariantBulkApplyField =
  | 'weight'
  | 'errorTolerance'
  | 'costNet'
  | 'price'
  | 'discountPct'
  | 'stock'
  | 'minOrder'
  | 'deliveryEstimate'
  | 'active';

export type ApplyVariantValueToAllResult = {
  variants: Variant[];
  changedVariantIds: string[];
  sourceVariant: Variant | null;
};

const updateVariantDeliveryEstimate = (
  variant: Variant,
  deliveryEstimate: string | null
): Variant => {
  const contentOverride = { ...(variant.contentOverride ?? {}) };
  if (deliveryEstimate) contentOverride.deliveryEstimate = deliveryEstimate;
  else delete contentOverride.deliveryEstimate;
  return {
    ...variant,
    contentOverride: Object.keys(contentOverride).length > 0 ? contentOverride : null
  };
};

export const applyVariantValueToAll = (
  variants: Variant[],
  sourceVariantId: string,
  field: VariantBulkApplyField
): ApplyVariantValueToAllResult => {
  const sourceVariant = variants.find((variant) => variant.id === sourceVariantId) ?? null;
  if (!sourceVariant || variants.length < 2) {
    return { variants, changedVariantIds: [], sourceVariant };
  }

  const changedVariantIds: string[] = [];
  const sourceDeliveryEstimate = sourceVariant.contentOverride?.deliveryEstimate?.trim() || null;
  const nextVariants = variants.map((variant) => {
    if (variant.id === sourceVariant.id) return variant;

    let nextVariant = variant;
    if (field === 'deliveryEstimate') {
      const currentDeliveryEstimate = variant.contentOverride?.deliveryEstimate?.trim() || null;
      if (currentDeliveryEstimate === sourceDeliveryEstimate) return variant;
      nextVariant = updateVariantDeliveryEstimate(variant, sourceDeliveryEstimate);
    } else if (field === 'weight') {
      const value = sourceVariant.weight ?? null;
      if ((variant.weight ?? null) === value) return variant;
      nextVariant = { ...variant, weight: value };
    } else if (field === 'errorTolerance') {
      const value = sourceVariant.errorTolerance ?? null;
      if ((variant.errorTolerance ?? null) === value) return variant;
      nextVariant = { ...variant, errorTolerance: value };
    } else if (field === 'costNet') {
      const value = sourceVariant.costNet ?? null;
      if ((variant.costNet ?? null) === value) return variant;
      nextVariant = { ...variant, costNet: value };
    } else if (field === 'price') {
      if (variant.price === sourceVariant.price) return variant;
      nextVariant = { ...variant, price: sourceVariant.price };
    } else if (field === 'discountPct') {
      if (variant.discountPct === sourceVariant.discountPct) return variant;
      nextVariant = { ...variant, discountPct: sourceVariant.discountPct };
    } else if (field === 'stock') {
      if (variant.stock === sourceVariant.stock) return variant;
      nextVariant = { ...variant, stock: sourceVariant.stock };
    } else if (field === 'minOrder') {
      const value = sourceVariant.minOrder ?? 1;
      if ((variant.minOrder ?? 1) === value) return variant;
      nextVariant = { ...variant, minOrder: value };
    } else if (field === 'active') {
      if (variant.active === sourceVariant.active) return variant;
      nextVariant = { ...variant, active: sourceVariant.active };
    }

    changedVariantIds.push(variant.id);
    return nextVariant;
  });

  return {
    variants: changedVariantIds.length > 0 ? nextVariants : variants,
    changedVariantIds,
    sourceVariant
  };
};

export const createFamily = (overrides: Partial<ProductFamily> = {}): ProductFamily => ({
  id: `fam-${Math.random().toString(36).slice(2, 10)}`,
  name: '',
  description: '',
  category: '',
  categoryId: null,
  subcategoryId: null,
  images: [],
  promoBadge: '',
  defaultDiscountPct: 0,
  active: true,
  sort: 1,
  notes: '',
  slug: '',
  defaultVariantId: null,
  optionAxes: [],
  variants: [createVariant()],
  ...overrides
});

const statusLabel = (active: boolean) => (active ? 'Aktiven' : 'Skrit');

const variantLabel = (variant: Variant) => buildVariantMeasurementName(variant);

function buildFamiliesFromSeed(seedItems: SeedItemTuple[]): ProductFamily[] {
  const grouped = new Map<string, ProductFamily>();

  seedItems.forEach((seed, index) => {
    const [id, name, description, category, categoryId, subcategoryId, price, sku, images, discountPct, displayOrder] = seed;
    const [familyRaw, variantRaw] = name.split(',').map((part) => part.trim());
    const dimensions = variantRaw ? parseDimensionTriplet(variantRaw) : { width: null, length: null, thickness: null };
    const familyName = familyRaw;
    const familySlug = toSlug(familyName);
    const key = `${familySlug}::${categoryId ?? category}`;

    const variant = createVariant({
      id,
      label: variantRaw || 'Osnovna različica',
      width: dimensions.width,
      length: dimensions.length,
      thickness: dimensions.thickness,
      sku,
      price,
      discountPct,
      stock: Math.max(0, 40 - index),
      active: true,
      sort: index + 1
    });

    const existing = grouped.get(key);
    if (!existing) {
      grouped.set(
        key,
        createFamily({
          id: key,
          name: familyName,
          description,
          category,
          categoryId,
          subcategoryId,
          images,
          promoBadge: discountPct > 0 ? 'Akcija' : '',
          defaultDiscountPct: discountPct,
          active: true,
          sort: displayOrder ?? index + 1,
          slug: familySlug,
          variants: [variant]
        })
      );
      return;
    }

    grouped.set(key, {
      ...existing,
      images: existing.images.length ? existing.images : images,
      defaultDiscountPct: existing.defaultDiscountPct || discountPct,
      variants: [...existing.variants, variant]
    });
  });

  return Array.from(grouped.values()).map((family) => ({
    ...family,
    variants: [...family.variants]
      .sort((a, b) => a.sort - b.sort)
      .map((variant, index) => ({ ...variant, label: buildVariantMeasurementName(variant), sort: index + 1 }))
  }));
}
