'use client';
import { useMemo, useRef, useState, type ClipboardEvent, type KeyboardEvent } from 'react';
import { ArrowDown, ArrowUp, Download, ExternalLink, Filter, SlidersHorizontal } from 'lucide-react';
import { AdminTableLayout, ColumnVisibilityControl, adminTableCardClassName, adminTableCardStyle, adminTableSearchInputClassName, adminTableSearchIconClassName } from '@/shared/ui/admin-table';
import { AdminSearchInput } from '@/shared/ui/admin-search-input';
import { AdminCheckbox } from '@/shared/ui/checkbox';
import { EuiTablePagination } from '@/shared/ui/pagination';
import { HEADER_FILTER_BUTTON_CLASS, HeaderFilterPortal, getHeaderPopoverStyle, useHeaderFilterDismiss } from '@/shared/ui/admin-header-filter';
import { AdminSwitch } from '@/shared/ui/admin-switch';
import { downloadTableAsCsv } from '@/shared/utils/table-export';
import { comparePricingStockDecimals, type PricingStockModel, type previewPricingStockBulk } from '@/shared/domain/pricingStock';
import type { PricingStockRow } from '@/shared/domain/pricingStock/api';
import PricingBulkActions from './PricingBulkActions';
import { decimalText, fieldLabels, money, percent, rowLabel, timestamp, type EditableField } from './viewHelpers';
import { formatSlCount } from '@/shared/domain/formatting';
import styles from './PricingStock.module.css';
export type CellDrafts = Record<number, Partial<Record<EditableField,string>>>;
export type CellErrors = Record<string,string>;
type Column = {key:string;label:string;width:number;editable?:EditableField;optional?:boolean;sort?:boolean};
const columns:Column[]=[
  {key:'identity',label:'Artikel',width:265,sort:true}, {key:'inventory',label:'Zaloga',width:92,editable:'inventory',sort:true},
  {key:'purchaseNet',label:'Nabavna cena',width:120,editable:'purchaseNet',sort:true},{key:'saleNet',label:'Prodajna cena',width:120,editable:'saleNet',sort:true},
  {key:'rvc',label:'RVC',width:92,sort:true},{key:'workMinutes',label:'Delo / kos',width:105,editable:'workMinutes',sort:true},
  {key:'otherCosts',label:'Drugi stroški',width:120,editable:'otherCosts',optional:true,sort:true},{key:'targetRvc',label:'Ciljna RVC',width:100,sort:true},
  {key:'coveragePercent',label:'Pokritje',width:167,sort:true},{key:'recommendedPrice',label:'Priporočena cena',width:116,optional:true,sort:true},
  {key:'purchaseUpdatedAt',label:'Posodobljeno',width:120,optional:true,sort:true},{key:'reserved',label:'Rezervirano',width:95,optional:true,sort:true},
  {key:'available',label:'Razpoložljivo',width:100,optional:true,sort:true},{key:'edit',label:'Uredi',width:46}
];
const coverageOptions=[['all','Vsa pokritja'],['below','Pod pragom'],['borderline','Na meji'],['adequate','Ustrezno'],['missing','Ni podatkov']];
const stockOptions=[['all','Vsa zaloga'],['zero','Brez zaloge'],['positive','Na zalogi']];
const normalized=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('sl-SI');
function sortValue(row:PricingStockRow,key:string):string|number|null {if(key==='identity')return rowLabel(row);if(key==='purchaseUpdatedAt')return row.purchaseUpdatedAt;if(['rvc','targetRvc','coveragePercent','recommendedPrice'].includes(key))return row.calculation[key as 'rvc'];return row[key as 'inventory'];}
type Props={rows:PricingStockRow[];drafts:CellDrafts;errors:CellErrors;changed:Set<number>;modelDirty:boolean;model:PricingStockModel;selected:Set<number>;onSelect:(ids:Set<number>)=>void;stockEnabled:boolean;canEditPrices:boolean;canEditCosts:boolean;canEditStock:boolean;busy:boolean;onStockToggle:(enabled:boolean)=>void;onEdit:(id:number,field:EditableField,value:string)=>void;onPaste:(id:number,field:EditableField,text:string,ordered:PricingStockRow[],fields:EditableField[])=>void;onBulk:(rows:ReturnType<typeof previewPricingStockBulk>['rows'])=>void;onSave:()=>void;onReset:()=>void;saveDisabled:boolean;onOpen:(row:PricingStockRow)=>void};
export default function PricingStockGrid(props:Props){
  const {rows,drafts,errors,changed,modelDirty,selected,onSelect,model,stockEnabled,canEditPrices,canEditCosts,canEditStock,busy}=props;
  const [search,setSearch]=useState(''),[category,setCategory]=useState('all'),[stock,setStock]=useState('all'),[coverage,setCoverage]=useState('all'),[problems,setProblems]=useState(false),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(20);
  const [visible,setVisible]=useState<Record<string,boolean>>(()=>Object.fromEntries(columns.map(column=>[column.key,!column.optional]))),[sort,setSort]=useState<{key:string;direction:1|-1}>({key:'identity',direction:1}),[filter,setFilter]=useState<'category'|'stock'|'coverage'|null>(null);
  const anchor=useRef<HTMLElement|null>(null),table=useRef<HTMLTableElement>(null);
  useHeaderFilterDismiss({isOpen:filter!==null,onClose:()=>setFilter(null)});
  const shownColumns=columns.filter(column=>visible[column.key]),editableColumns=shownColumns.flatMap(column=>column.editable&&((column.editable==='inventory'&&stockEnabled&&canEditStock)||(column.editable==='saleNet'?canEditPrices:column.editable!=='inventory'&&canEditCosts))?[column.editable]:[]);
  const filtered=useMemo(()=>rows.filter(row=>{const query=normalized(search);return(!query||normalized(rowLabel(row)+' '+(row.sku??'')).includes(query))&&(category==='all'||(row.categoryId??'uncategorized')===category)&&(stock==='all'||(stock==='zero'?row.inventory===0:row.inventory>0))&&(coverage==='all'||row.calculation.status===coverage)&&(!problems||row.calculation.status!=='adequate'||row.inventory===0);}).sort((a,b)=>{const x=sortValue(a,sort.key),y=sortValue(b,sort.key);if(x===null||x===undefined)return y===null||y===undefined?0:1;if(y===null||y===undefined)return-1;return(sort.key==='identity'||sort.key==='purchaseUpdatedAt'?String(x).localeCompare(String(y),'sl-SI'):comparePricingStockDecimals(String(x),String(y)))*sort.direction;}),[rows,search,category,stock,coverage,problems,sort]);
  const pageCount=Math.max(1,Math.ceil(filtered.length/pageSize)),safePage=Math.min(page,pageCount),visibleRows=filtered.slice((safePage-1)*pageSize,safePage*pageSize),selectedRows=rows.filter(row=>selected.has(row.variantId));
  const categories=useMemo(()=>Array.from(new Map(rows.map(row=>[row.categoryId??'uncategorized',row.categoryLabel||'Brez kategorije'])).entries()).sort((a,b)=>a[1].localeCompare(b[1],'sl-SI')),[rows]);
  const allSelected=visibleRows.length>0&&visibleRows.every(row=>selected.has(row.variantId));
  const toggleRow=(id:number)=>{const next=new Set(selected);if(next.has(id))next.delete(id);else next.add(id);onSelect(next);};
  const keyDown=(event:KeyboardEvent<HTMLInputElement>)=>{if(event.key!=='Tab'||event.ctrlKey||event.metaKey||event.altKey)return;const inputs=Array.from(table.current?.querySelectorAll<HTMLInputElement>('input[data-pricing-cell]:not(:disabled)')??[]),index=inputs.indexOf(event.currentTarget),next=inputs[index+(event.shiftKey?-1:1)];if(next){event.preventDefault();next.focus();next.select();}};
  const paste=(event:ClipboardEvent<HTMLInputElement>,row:PricingStockRow,field:EditableField)=>{const text=event.clipboardData.getData('text/plain');if(!text.includes('\t')&&!/[\r\n]/.test(text))return;event.preventDefault();props.onPaste(row.variantId,field,text,filtered,editableColumns);};
  const openFilter=(kind:typeof filter,target:HTMLElement)=>{anchor.current=target;setFilter(filter===kind?null:kind);};
  const exportRows=()=>{const source=selectedRows.length?selectedRows:filtered;downloadTableAsCsv([['Artikel','SKU','Zaloga','Nabavna cena brez DDV','Prodajna cena brez DDV','RVC','Ciljna RVC','Pokritje %'],...source.map(row=>[rowLabel(row),row.sku??'',String(row.inventory),row.purchaseNet??'',row.saleNet??'',row.calculation.rvc??'',row.calculation.targetRvc??'',row.calculation.coveragePercent??''])],'cene-in-zaloga.csv');};
  const options=filter==='category'?[['all','Vse kategorije'],...categories]:filter==='stock'?stockOptions:coverageOptions;
  const activeFilter=filter==='category'?category:filter==='stock'?stock:coverage;
  const selectFilter=(value:string)=>{if(filter==='category')setCategory(value);if(filter==='stock')setStock(value);if(filter==='coverage')setCoverage(value);setPage(1);setFilter(null);};
  return <AdminTableLayout className={`${adminTableCardClassName} ${styles.tableCard}`} style={adminTableCardStyle} headerClassName="!px-3 !py-2" contentClassName={styles.tableContent}
    headerLeft={<div className="flex min-w-0 flex-1 items-center gap-3"><AdminSearchInput value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} placeholder="Poišči artikel ali SKU …" aria-label="Poišči artikel ali SKU" wrapperClassName="!h-9 min-w-0 !w-full max-w-[390px] !rounded-md !bg-slate-50" inputClassName={adminTableSearchInputClassName} iconClassName={adminTableSearchIconClassName}/><label className="inline-flex shrink-0 items-center gap-1.5 whitespace-nowrap text-[11px]"><AdminCheckbox checked={problems} onChange={()=>{setProblems(v=>!v);setPage(1);}}/>Samo težave</label></div>}
    headerRight={<div className={styles.actions}><ColumnVisibilityControl options={columns.filter(c=>c.key!=='edit').map(c=>({key:c.key,label:c.label,disabled:c.key==='identity'}))} visibleMap={visible} onToggle={key=>setVisible(current=>({...current,[key]:!current[key]}))} showLabel={false} icon={<SlidersHorizontal size={15}/>} triggerClassName="!h-9 !w-9 !rounded-md"/><button type="button" className={styles.button} onClick={exportRows} title="Izvoz prikazanih ali izbranih vrstic" aria-label="Izvozi cene in zalogo"><Download size={15}/></button><button type="button" className={styles.primary} disabled={props.saveDisabled} onClick={props.onSave}>{busy?'Shranjujem …':'Shrani spremembe'}</button></div>}
    filterRowLeft={selectedRows.length?<PricingBulkActions rows={selectedRows} model={model} stockEnabled={stockEnabled&&canEditStock} canEditPrices={canEditPrices} canEditCosts={canEditCosts} disabled={busy} onApply={props.onBulk}/>:<span className="text-[10px] text-slate-500">{formatSlCount(filtered.length,{one:'različica',two:'različici',few:'različice',other:'različic'})} · RVC je razlika v ceni, ni dobiček.</span>}
    filterRowRight={<div className="flex items-center gap-2 text-[10px]"><span title={stockEnabled?'Zaloga omejuje naročanje.':'Zaloga je informativna. Urejanje zaloge je izključeno.'}>Omejevanje zaloge</span><AdminSwitch checked={stockEnabled} disabled={busy||!canEditStock} ariaLabel="Omejevanje zaloge pri naročanju" onChange={props.onStockToggle}/></div>} showDivider={false}
    footerRight={<div className={styles.footer}><span role="status">{[changed.size?formatSlCount(changed.size,{one:'neshranjena vrstica',two:'neshranjeni vrstici',few:'neshranjene vrstice',other:'neshranjenih vrstic'}):'',modelDirty?'Neshranjen model':''].filter(Boolean).join(' · ')||'Vse spremembe so shranjene'}</span><div className={styles.footerActions}><button type="button" className={styles.button} disabled={busy||(changed.size===0&&!modelDirty)} onClick={props.onReset}>Razveljavi</button><button type="button" className={styles.primary} disabled={props.saveDisabled} onClick={props.onSave}>Shrani spremembe</button></div><EuiTablePagination page={safePage} pageCount={pageCount} onPageChange={setPage} itemsPerPage={pageSize} onChangeItemsPerPage={next=>{setPageSize(next);setPage(1);}} itemsPerPageOptions={[20,50,100]}/></div>}>
    <table ref={table} className={styles.table} style={{minWidth:shownColumns.reduce((sum,column)=>sum+column.width,36)}} aria-label="Cene in zaloga različic" data-testid="pricing-stock-table"><colgroup><col style={{width:36}}/>{shownColumns.map(column=><col key={column.key} style={{width:column.key==='edit'?column.width:((column.width/(shownColumns.filter(c=>c.key!=='edit').reduce((sum,c)=>sum+c.width,0)))*100)+'%'}}/>)}</colgroup><thead><tr><th className={styles.selection}><AdminCheckbox checked={allSelected} aria-label="Izberi prikazane različice" onChange={()=>{const next=new Set(selected);visibleRows.forEach(row=>{if(allSelected)next.delete(row.variantId);else next.add(row.variantId);});onSelect(next);}}/></th>{shownColumns.map(column=><th key={column.key} className={column.key==='identity'?styles.identity:undefined} aria-sort={sort.key===column.key?(sort.direction===1?'ascending':'descending'):undefined}><div className={styles.headerControl}><button type="button" className={styles.sortButton} disabled={!column.sort} onClick={()=>setSort(current=>({key:column.key,direction:current.key===column.key&&current.direction===1?-1:1}))}>{column.label}{['purchaseNet','saleNet'].includes(column.key)&&<small>brez DDV</small>}{sort.key===column.key&&(sort.direction===1?<ArrowUp className="ml-1 inline" size={10}/>:<ArrowDown className="ml-1 inline" size={10}/>)}</button>{['identity','inventory','coveragePercent'].includes(column.key)&&<button type="button" data-header-filter-root="true" className={HEADER_FILTER_BUTTON_CLASS} aria-label={column.key==='identity'?'Filtriraj po kategoriji':column.key==='inventory'?'Filtriraj po zalogi':'Filtriraj po pokritju'} aria-expanded={filter===(column.key==='identity'?'category':column.key==='inventory'?'stock':'coverage')} onClick={e=>openFilter(column.key==='identity'?'category':column.key==='inventory'?'stock':'coverage',e.currentTarget)}><Filter size={12}/></button>}</div></th>)}</tr></thead>
      <tbody>{visibleRows.map(row=><tr key={row.variantId} className={changed.has(row.variantId)?styles.changed:selected.has(row.variantId)?styles.selected:undefined} data-variant-id={row.variantId}><td className={styles.selection}><AdminCheckbox checked={selected.has(row.variantId)} aria-label={'Izberi '+rowLabel(row)} onChange={()=>toggleRow(row.variantId)}/></td>{shownColumns.map(column=>{
        if(column.key==='identity')return <td key={column.key} className={styles.identity} title={rowLabel(row)+' · '+row.categoryLabel}><strong>{rowLabel(row)}</strong><small>{row.sku||'Brez SKU'}</small></td>;
        if(column.editable){const field=column.editable,error=errors[`${row.variantId}:${field}`],isStock=field==='inventory',isDisabled=busy||(isStock?(!stockEnabled||!canEditStock):field==='saleNet'?!canEditPrices:!canEditCosts),unit=field==='workMinutes'?'min':field==='inventory'?null:'€';return <td key={column.key} title={error||(isStock&&!stockEnabled?'Urejanje je izključeno, ker je zaloga informativna.':field==='purchaseNet'?'Trenutna nabavna cena brez DDV na enoto. Posodobljeno: '+timestamp(row.purchaseUpdatedAt):fieldLabels[field])}><div className="relative"><input className={styles.editCell} style={{paddingRight:unit?24:6}} data-pricing-cell={`${row.variantId}:${field}`} inputMode={isStock?'numeric':'decimal'} aria-label={`${fieldLabels[field]} · ${row.sku||rowLabel(row)}`} aria-invalid={!!error} disabled={isDisabled} value={decimalText(drafts[row.variantId]?.[field]??row[field])} placeholder="—" onFocus={e=>e.currentTarget.select()} onChange={e=>props.onEdit(row.variantId,field,e.target.value)} onKeyDown={keyDown} onPaste={e=>paste(e,row,field)}/>{unit&&<span className="pointer-events-none absolute right-1.5 top-1.5 text-[9px] text-slate-500">{unit}</span>}</div></td>;}
        if(column.key==='rvc')return <td key={column.key} className={styles.number}>{money(row.calculation.rvc)}<small>{percent(row.calculation.rvcPercent)}</small></td>;
        if(column.key==='targetRvc'||column.key==='recommendedPrice')return <td key={column.key} className={styles.number}>{money(row.calculation[column.key])}</td>;
        if(column.key==='coveragePercent')return <td key={column.key} title={row.calculation.errors.filter(issue=>issue.code!=='MISSING_VALUE').map(issue=>issue.message).join(' ')||(row.calculation.status==='missing'?'Za izračun vnesite ceni, čas dela in druge stroške. Druge stroške vključite z izbiro stolpcev.':'RVC / ciljna RVC; razlika je RVC minus ciljna RVC.')}><div className={`${styles.coverage} ${styles[row.calculation.status]}`}><i aria-hidden="true"/><div><span>{row.calculation.coveragePercent!==null?percent(row.calculation.coveragePercent)+' · ':''}{row.calculation.statusLabel}</span><small>{money(row.calculation.difference)}</small></div></div></td>;
        if(column.key==='purchaseUpdatedAt')return <td key={column.key} className="text-[10px] text-slate-500" title="Čas zadnje spremembe nabavne cene">{timestamp(row.purchaseUpdatedAt)}</td>;
        if(column.key==='reserved'||column.key==='available')return <td key={column.key} className={styles.number} title={row.reservationNote??(column.key==='available'?'Razpoložljiva zaloga za nova naročila.':'Potrjene odprte rezervacije.')}>{row[column.key]===null?'—':row[column.key]}</td>;
        return <td key={column.key} className="text-center"><button type="button" title="Odpri urejanje artikla" aria-label={'Uredi '+rowLabel(row)} className="inline-flex h-7 w-7 items-center justify-center rounded text-slate-500 hover:bg-slate-100 hover:text-blue-600" onClick={()=>props.onOpen(row)}><ExternalLink size={14}/></button></td>;
      })}</tr>)}{visibleRows.length===0&&<tr><td colSpan={shownColumns.length+1} className={styles.empty}>Nobena različica ne ustreza izbranim filtrom.</td></tr>}</tbody>
    </table>
    <HeaderFilterPortal open={filter!==null}><div role="menu" className={styles.filterPanel} style={getHeaderPopoverStyle(anchor.current,240)} aria-label={filter==='category'?'Kategorija':filter==='stock'?'Zaloga':'Pokritje'}>{options.map(([value,label])=><button key={value} type="button" role="menuitemradio" aria-checked={activeFilter===value} className={activeFilter===value?styles.filterActive:undefined} onClick={()=>selectFilter(value)}>{label}</button>)}</div></HeaderFilterPortal>
  </AdminTableLayout>;
}
