import { expect } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { test } from 'node:test';
import {
  createVariant,
  duplicateSelectedVariant,
  type Variant
} from '@/admin/features/artikli/lib/familyModel';

const createFixtureVariants = (): Variant[] => [
  createVariant({
    id: 'variant-source',
    label: '0,5 × 100 × 100 mm',
    width: 100,
    length: 100,
    thickness: 0.5,
    errorTolerance: '0,1',
    weight: 24,
    minOrder: 2,
    sku: 'MAT-001',
    skuAutoGenerated: true,
    price: 12,
    costNet: 8,
    discountPct: 5,
    stock: 20,
    active: true,
    sort: 1,
    contentOverride: {
      description: 'Opis različice',
      specifications: { Material: 'Aluminij' },
      attributes: { Barva: 'Srebrna' },
      includedItems: ['Plošča'],
      deliveryEstimate: '1–2 dni',
      documentIds: [10]
    },
    imageAssignments: [101],
    optionValueIds: [201],
    optionSelections: { debelina: '05' }
  }),
  createVariant({
    id: 'variant-existing-copy',
    label: 'Obstoječa kopija',
    sku: 'mat-001-kopija',
    active: false,
    sort: 2
  }),
  createVariant({
    id: 'variant-copy-id',
    label: 'Druga različica',
    sku: 'MAT-002',
    active: true,
    sort: 3
  })
];

test('variant duplication is unavailable for zero or multiple selections', () => {
  const variants = createFixtureVariants();
  const before = structuredClone(variants);

  const withoutSelection = duplicateSelectedVariant(
    variants,
    [],
    () => 'unused-id'
  );
  const withMultipleSelection = duplicateSelectedVariant(
    variants,
    ['variant-source', 'variant-existing-copy'],
    () => 'unused-id'
  );

  expect(withoutSelection.duplicatedVariant).toBeNull();
  expect(withoutSelection.variants).toBe(variants);
  expect(withMultipleSelection.duplicatedVariant).toBeNull();
  expect(withMultipleSelection.variants).toBe(variants);
  expect(variants).toEqual(before);
});

test('the dimensional variant toolbar exposes one accessible duplicate action and disables invalid selection counts', () => {
  const editorSource = readFileSync(
    resolve(
      process.cwd(),
      'src/admin/features/artikli/components/AdminItemEditorPage.tsx'
    ),
    'utf8'
  );
  const duplicateButton = editorSource.match(
    /<IconButton\s+type="button"\s+aria-label="Podvoji izbrano različico"[\s\S]*?<\/IconButton>/
  )?.[0];

  expect(duplicateButton).toBeDefined();
  expect(duplicateButton).toContain('title="Podvoji izbrano različico"');
  expect(duplicateButton).toContain(
    'disabled={!isTableEditable || variantSelections.size !== 1}'
  );
  expect(duplicateButton).toContain(
    'onClick={duplicateSelectedDimensionVariant}'
  );
  expect(duplicateButton).toContain('<CopyIcon />');
  expect(editorSource).toContain(
    'if (!isTableEditable || variantSelections.size !== 1) return;'
  );
});

test('variant duplication appends one inactive, uniquely identified deep clone without mutating its source', () => {
  const variants = createFixtureVariants();
  const before = structuredClone(variants);

  const result = duplicateSelectedVariant(
    variants,
    ['variant-source'],
    () => 'variant-copy-id'
  );
  const clone = result.duplicatedVariant;

  expect(clone).not.toBeNull();
  expect(result.variants).toHaveLength(variants.length + 1);
  expect(result.variants.at(-1)).toBe(clone);
  expect(clone).toMatchObject({
    id: 'variant-copy-id-2',
    sku: 'MAT-001-KOPIJA-2',
    skuAutoGenerated: false,
    active: false,
    label: before[0].label,
    width: before[0].width,
    length: before[0].length,
    thickness: before[0].thickness,
    weight: before[0].weight,
    price: before[0].price,
    stock: before[0].stock,
    sort: 4
  });
  expect(result.variants.map((variant) => variant.sort)).toEqual([1, 2, 3, 4]);
  expect(new Set(result.variants.map((variant) => variant.id)).size).toBe(
    result.variants.length
  );
  expect(
    new Set(
      result.variants.map((variant) =>
        variant.sku.trim().toLocaleLowerCase('sl')
      )
    ).size
  ).toBe(result.variants.length);
  expect(variants).toEqual(before);

  clone!.contentOverride!.includedItems!.push('Dodatek');
  clone!.imageAssignments!.push(102);
  clone!.optionValueIds!.push(202);
  clone!.optionSelections!.barva = 'srebrna';

  expect(variants).toEqual(before);
});
