import assert from 'node:assert/strict';
import test from 'node:test';
import { resolveBusinessPeriod, localDate, localInstant, calendarDates } from '../../src/shared/domain/analytics/period';
import { binomial, describe, distributionFit, empiricalCdf, histogram, logisticFit, ols, wilson, zScore } from '../../src/shared/domain/analytics/statistics';
import { aggregateBusinessAnalytics, quoteDeadline } from '../../src/shared/domain/analytics/metrics';
import type { BusinessFilters, CanonicalOrder, CanonicalQuote } from '../../src/shared/domain/analytics/businessAnalytics';
const filters: BusinessFilters = { range: '30D', customerType: 'all', status: 'all', source: 'all' };
const asOf = new Date('2026-09-05T10:00:00.000Z');
const order = (override: Partial<CanonicalOrder> = {}): CanonicalOrder => ({ id: '1', number: 'N-1', submittedAt: '2026-08-20T12:00:00.000Z', fulfilledAt: '2026-08-22T12:00:00.000Z', customerKey: 'school:branch-1', customerType: 'school', customerName: 'Šola', activityCents: 10000, fulfilledCents: 10000, refundCents: 0, refundComplete: true, status: 'finished', source: 'direct', addressSnapshot: {}, snapshotOrigin: 'captured', shippingGrossCents: 610, shippingTaxRate: .22, shippingSnapshot: null, packedWeightGrams: null, carrierCostNetCents: null, parcelCount: null, preparationMinutes: null, oversize: null, lines: [{ id: '1', key: 'variant:1', name: 'Pripomoček', category: 'Učenje', quantity: 2, lineNetCents: 10000, unitCostCents: null }], ...override });
const quote = (override: Partial<CanonicalQuote> = {}): CanonicalQuote => ({ id: 'q1', number: 'POV-1', createdAt: '2026-08-01T12:00:00.000Z', firstIssuedAt: '2026-08-03T12:00:00.000Z', acceptedAt: '2026-08-10T12:00:00.000Z', initialValueCents: 10000, customerType: 'school', customerName: 'Šola', mature: true, acceptedInWindow: true, ...override });
function aggregate(orders: CanonicalOrder[], quotes: CanonicalQuote[] = [], override: Partial<BusinessFilters> = {}) { const applied = { ...filters, ...override }; return aggregateBusinessAnalytics({ allOrders: orders, quotes, filters: applied, period: resolveBusinessPeriod(applied, asOf), asOf: asOf.toISOString() }); }

test('all presets use local dates including today, calendar years and leap-day clamp', () => {
  for (const [range, count] of [['30D', 30], ['90D', 90], ['180D', 180]] as const) { const period = resolveBusinessPeriod({ range }, asOf); assert.equal(period.dayCount, count); assert.equal(period.to, '2026-09-05'); assert.equal(period.endExclusive, asOf.toISOString()); assert.equal(period.partialToday, true); }
  assert.equal(resolveBusinessPeriod({ range: '1Y' }, new Date('2024-02-29T12:00:00Z')).from, '2023-03-01');
  assert.equal(resolveBusinessPeriod({ range: '2Y' }, new Date('2024-02-29T12:00:00Z')).from, '2022-03-01');
  const ytd = resolveBusinessPeriod({ range: 'YTD' }, new Date('2024-02-29T12:00:00Z')); assert.equal(ytd.from, '2024-01-01'); assert.equal(ytd.comparison.to, '2023-02-28');
  assert.equal(localDate(new Date('2026-12-31T23:30:00Z')), '2027-01-01');
});
test('Ljubljana custom dates include both dates with DST midnight boundaries', () => {
  const spring = resolveBusinessPeriod({ range: 'custom', from: '2026-03-29', to: '2026-03-29' }, asOf); assert.equal(spring.start, '2026-03-28T23:00:00.000Z'); assert.equal(spring.endExclusive, '2026-03-29T22:00:00.000Z'); assert.equal(spring.dayCount, 1);
  const fall = resolveBusinessPeriod({ range: 'custom', from: '2025-10-26', to: '2025-10-26' }, asOf); assert.equal(Date.parse(fall.endExclusive) - Date.parse(fall.start), 25 * 3600000);
  const partial = resolveBusinessPeriod({ range: '30D' }, new Date('2026-03-30T09:15:00Z')); assert.equal(partial.comparison.endExclusive, '2026-02-28T10:15:00.000Z');
  assert.equal(localInstant('2026-03-30').toISOString(), '2026-03-29T22:00:00.000Z');
  assert.equal(calendarDates('2023-12-31', '2024-01-01').length, 2);
  assert.throws(() => resolveBusinessPeriod({ range: 'custom', from: '2026-02-30', to: '2026-03-01' }, asOf));
});
test('statistics retain missing observations, quantile type 7 and population/sample conventions', () => {
  const empty = describe([null]); assert.equal(empty.mean, null); assert.equal(empty.missing, 1);
  const one = describe([5]); assert.equal(one.variance, 0); assert.equal(one.sampleVariance, null); assert.equal(zScore(5, one), null);
  const stats = describe([1, 2, 3, 4, null]); assert.equal(stats.q1, 1.75); assert.equal(stats.q3, 3.25); assert.equal(stats.variance, 1.25); assert.equal(stats.sampleVariance, 5 / 3); assert.equal(stats.missing, 1);
  assert.equal(histogram([5, 5, null]).length, 1); assert.equal(histogram([1, 2, 10000], 10).reduce((sum, bin) => sum + bin.count, 0), 3);
  assert.deepEqual(empiricalCdf([1, 1, 3]), [{ value: 1, probability: 2 / 3 }, { value: 3, probability: 1 }]);
});
test('regression uses the same complete pairs and constant variables remain explicit', () => { const fit = ols([{ x: 1, y: 2 }, { x: 2, y: 4 }, { x: 3, y: 6 }, { x: 100, y: null }]); assert.equal(fit.n, 3); assert.equal(fit.missing, 1); assert.equal(fit.slope, 2); assert.equal(fit.intercept, 0); assert.equal(fit.rSquared, 1); assert.equal(fit.covariance, 4 / 3); assert.equal(ols([{ x: 1, y: 2 }, { x: 1, y: 4 }]).slope, null); assert.equal(ols([{ x: 1, y: 2 }, { x: 2, y: 2 }]).r, null); });
test('binomial remains normalized at extremes and validates assumptions domain', () => { for (const [n, p] of [[0, .5], [10, 0], [10, 1], [10000, .0001], [10000, .99]]) { const model = binomial(n, p, 0); assert.ok(Math.abs(model.probabilities.reduce((sum, value) => sum + value, 0) - 1) < 1e-10); assert.ok(Math.abs(model.tail - 1) < 1e-10); } assert.equal(binomial(10, 1, 11).tail, 0); assert.throws(() => binomial(1.1, .5, 1)); assert.throws(() => binomial(2, 1.1, 1)); assert.equal(wilson(0, 0).rate, null); assert.ok(wilson(0, 10).upper! > 0); });
test('candidate fits exclude nonpositive log observations and reject separated/tiny logistic data', () => { const fit = distributionFit([-1, 0, 1, 2, 2]); assert.equal(fit.positiveCount, 3); assert.equal(fit.excluded, 2); assert.notEqual(fit.qqRaw.at(-1)?.theoretical, fit.qqRaw.at(-2)?.theoretical); assert.equal(logisticFit([{ value: 1, accepted: true }]).available, false); const separated = Array.from({ length: 40 }, (_, i) => ({ value: i, accepted: i > 19 })); assert.equal(logisticFit(separated).available, false); });
test('same activity cohort retains cancellation and exact cents, realised partial refunds revise fulfilment cohort', () => { const result = aggregate([order(), order({ id: '2', activityCents: 20001, fulfilledCents: 20001, refundCents: 5000, status: 'cancelled', source: 'quote' })]); assert.equal(result.summary.orderCount, 2); assert.equal(result.summary.activityValue, 300.01); assert.equal(result.summary.realisedValue, 250.01); assert.equal(result.days.reduce((sum, day) => sum + day.orderCount, 0), 2); assert.equal(result.orders.statistics.n, 2); assert.equal(result.orders.histogram.reduce((sum, bin) => sum + bin.count, 0), 2); assert.equal(aggregate([order(), order({ id: '2', status: 'cancelled' })], [], { status: 'cancelled' }).summary.orderCount, 1); });
test('unlinked customers never form a giant customer and refund/cost/time data remain missing', () => { const result = aggregate([order({ customerKey: null, refundComplete: false, refundCents: null }), order({ id: '2', customerKey: null })]); assert.equal(result.customers.totalCustomers, 0); assert.equal(result.customers.unlinkedOrders, 2); assert.equal(result.summary.realisedValue, null); assert.equal(result.products.points[0].contributionPerUnit, null); assert.equal(result.products.costCoveredUnits, 0); assert.equal(result.shipping.usable, 0); assert.equal(result.workload.regression.n, 0); });
test('quotes use first-issued mature cohort, retain immature separately, and match band denominators', () => { const q1 = quote({ firstIssuedAt: '2026-08-06T09:00:00.000Z' }); const q2 = quote({ id: 'q2', firstIssuedAt: '2026-08-30T09:00:00.000Z', mature: false, acceptedAt: null, acceptedInWindow: false }); const q3 = quote({ id: 'q3', firstIssuedAt: '2026-08-06T09:00:00.000Z', initialValueCents: 50000, acceptedAt: null, acceptedInWindow: false }); const result = aggregate([], [q1, q2, q3], { range: '90D' }); assert.equal(result.quotes.mature.total, 2); assert.equal(result.quotes.mature.accepted, 1); assert.equal(result.quotes.immature, 1); assert.equal(result.quotes.byValue.reduce((sum, band) => sum + band.total, 0), 2); assert.equal(result.quotes.decisionStatistics.n, 1); assert.equal(aggregate([], [q1], { source: 'direct' }).summary.quoteAcceptance.rate, null); assert.equal(quoteDeadline('2026-03-20T10:00:00Z'), '2026-04-19T10:00:00.000Z'); });
test('cohorts use full available linked history and future months unavailable', () => { const old = order({ id: 'old', fulfilledAt: '2026-01-01T10:00:00.000Z', submittedAt: '2026-01-01T09:00:00.000Z' }); const branch = order({ id: 'branch', customerKey: 'school:branch-2' }); const result = aggregate([old, order(), branch]); assert.equal(result.cohorts.rows.length, 1); assert.equal(result.cohorts.rows[0].customers, 1); assert.equal(result.cohorts.rows[0].month, '2026-08'); assert.equal(result.cohorts.rows[0].retention[2], null); assert.equal(result.customers.totalCustomers, 2); });
