'use client';

import { adminAnalyticsControlClassName, adminAnalyticsPanelClassName } from '@/shared/ui/theme/tokens';

import { useMemo, useState } from 'react';
import type { Data } from 'plotly.js';
import type { BusinessAnalyticsResponse } from '@/shared/domain/analytics/businessAnalytics';
import { binomial, zScore } from '@/shared/domain/analytics/statistics';
import { getCustomerTypeLabel } from '@/shared/domain/order/customerType';
import BusinessChart, { StatisticsDrawer, eur, numeric, percent, palette, type Drill } from './BusinessChart';
const control = adminAnalyticsControlClassName;
const drillData = (id: string) => JSON.stringify({ kind: 'orders', orderId: id });

export default function BusinessLaboratory({ data, onDrill, workloadOnly = false, onChange }: { data: BusinessAnalyticsResponse; query: string; onDrill: (drill: Drill) => void; workloadOnly?: boolean; onChange: (changes: Record<string, string | null>) => void }) {
  const [residuals, setResiduals] = useState(false);
  const [logarithmic, setLogarithmic] = useState(true);
  const [groupBy, setGroupBy] = useState<'customerType' | 'source'>('customerType');
  const [selectedId, setSelectedId] = useState('');
  const [distribution, setDistribution] = useState<'observed' | 'normal' | 'lognormal'>('observed');
  const [threshold, setThreshold] = useState('100');
  const [replayThreshold, setReplayThreshold] = useState('100');
  const [cdfVariable, setCdfVariable] = useState<'value' | 'weight'>('value');
  const [n, setN] = useState('20'); const [k, setK] = useState('10'); const [scenarioP, setScenarioP] = useState('0.5');
  const [pSource, setPSource] = useState(data.laboratory.binomialSource.rate == null ? 'scenario' : 'mature');
  const scenario = useMemo(() => {
    try { const probability = pSource === 'mature' ? data.laboratory.binomialSource.rate : Number(scenarioP); if (probability == null || n.trim() === '' || k.trim() === '' || (pSource === 'scenario' && scenarioP.trim() === '')) return { result: null, error: 'Dopolnite veljavne parametre scenarija.' }; return { result: binomial(Number(n), probability, Number(k)), error: null }; } catch (error) { return { result: null, error: error instanceof Error ? error.message : 'Neveljavni parametri.' }; }
  }, [n, k, scenarioP, pSource, data.laboratory.binomialSource.rate]);
  const paired = data.workload.points; const regression = data.workload.regression;
  const validX = paired.map(point => point.x); const minX = Math.min(...validX, 0); const maxX = Math.max(...validX, 0);
  const regressionData: Data[] = Array.from(new Set(paired.map(point => point[groupBy]))).map((group, index) => ({ type: 'scatter', mode: 'markers', name: groupBy === 'source' ? group === 'quote' ? 'Iz ponudbe' : 'Neposredno' : group === 'unknown' ? 'Neznano' : getCustomerTypeLabel(group), x: paired.filter(point => point[groupBy] === group).map(point => point.x), y: paired.filter(point => point[groupBy] === group).map(point => point.y), text: paired.filter(point => point[groupBy] === group).map(point => point.label), customdata: paired.filter(point => point[groupBy] === group).map(point => drillData(point.id)), marker: { color: palette[index % palette.length], size: 8, opacity: .75 } }));
  if (regression.slope != null && regression.intercept != null) {
    regressionData.push({ type: 'scatter', mode: 'lines', name: 'OLS', x: [minX, maxX], y: [regression.intercept + regression.slope * minX, regression.intercept + regression.slope * maxX], line: { color: '#0f172a', width: 1.5 } });
    if (residuals) regressionData.push({ type: 'scatter', mode: 'lines', name: 'Ostanki', x: paired.flatMap(point => [point.x, point.x, null]), y: paired.flatMap(point => [point.y, regression.intercept! + regression.slope! * point.x, null]), line: { color: '#cbd5e1', width: 1 }, hoverinfo: 'skip' });
  }
  if (regression.meanX != null && regression.meanY != null) regressionData.push({ type: 'scatter', mode: 'markers', name: 'Povprečna točka', x: [regression.meanX], y: [regression.meanY], marker: { size: 12, symbol: 'cross', color: '#b45309' } });
  const selected = data.laboratory.points.find(point => point.id === selectedId);
  const cdf = cdfVariable === 'value' ? data.laboratory.valueCdf : data.laboratory.weightCdf;
  const thresholdValue = Number(threshold);
  const cdfRate = Number.isFinite(thresholdValue) && cdf.length ? cdf.filter(point => point.value <= thresholdValue).at(-1)?.probability ?? 0 : null;
  const fit = data.laboratory.distribution;
  const distributionTraces: Data[] = [{ type: 'bar', name: 'Opazovana frekvenca', x: data.orders.histogram.map(bin => (bin.min + bin.max) / 2), y: data.orders.histogram.map(bin => bin.count), marker: { color: '#bbf7d0' }, customdata: data.orders.histogram.map(bin => JSON.stringify({ kind: 'orders', min: String(bin.min), max: String(bin.max), inclusiveMax: String(bin.last) })) }];
  const histogramWidth = data.orders.histogram[0] ? data.orders.histogram[0].max - data.orders.histogram[0].min : 0;
  const sampleCount = data.orders.statistics.n;
  if (distribution === 'normal' && fit.normal && fit.normal.variance > 0) {
    const normal = fit.normal;
    const points = Array.from({ length: 150 }, (_, index) => (data.orders.statistics.min ?? 0) + ((data.orders.statistics.max ?? 0) - (data.orders.statistics.min ?? 0)) * index / 149);
    distributionTraces.push({ type: 'scatter', mode: 'lines', name: 'Kandidat N(μ, σ²)', x: points, y: points.map(value => Math.exp(-.5 * (value - normal.mean) ** 2 / normal.variance) / Math.sqrt(2 * Math.PI * normal.variance) * histogramWidth * sampleCount), line: { color: '#2563eb' } });
  }
  if (distribution === 'lognormal' && fit.lognormal && fit.lognormal.logVariance > 0) {
    const model = fit.lognormal; const positive = data.laboratory.valueCdf.filter(point => point.value > 0); const low = positive[0]?.value ?? 1; const high = positive.at(-1)?.value ?? 1;
    const points = Array.from({ length: 150 }, (_, index) => low + (high - low) * index / 149);
    distributionTraces.push({ type: 'scatter', mode: 'lines', name: 'Kandidat lognormalne porazdelitve', x: points, y: points.map(value => Math.exp(-.5 * (Math.log(value) - model.logMean) ** 2 / model.logVariance) / (value * Math.sqrt(2 * Math.PI * model.logVariance)) * histogramWidth * fit.positiveCount), line: { color: '#2563eb' } });
  }
  const labPoints = data.laboratory.points.filter(point => !logarithmic || point.y > 0);
  return <div className="space-y-4">
    <div className="flex flex-wrap items-center gap-3 text-xs text-slate-600"><label className="flex items-center gap-2">Barva skupin<select className={control} value={groupBy} onChange={event => setGroupBy(event.target.value as 'customerType' | 'source')}><option value="customerType">Tip naročnika</option><option value="source">Izvor naročila</option></select></label><label className="flex items-center gap-2"><input type="checkbox" checked={residuals} onChange={event => setResiduals(event.target.checked)} />Prikaži ostanke OLS</label></div>
    <BusinessChart title="Obremenitev pri pripravi naročil" description={`Različne vrstice naročila in dejanske minute ročnega dela. Veljavni pari ${data.workload.usable}/${data.workload.total}; prikazanih ${paired.length}. Povzetek uporablja vse veljavne pare. Opazovana povezanost ne dokazuje vzročnega učinka.`} data={regressionData} xTitle="Različne vrstice naročila" yTitle="Ročna priprava (minute)" columns={['Naročilo', 'Vrstice', 'Minute priprave', 'Ostanek (minute)']} rows={paired.map(point => ({ values: [point.label, point.x, point.y, regression.slope == null || regression.intercept == null ? null : point.y - (regression.intercept + regression.slope * point.x)], href: point.href }))} onDrill={onDrill} empty={!paired.length}>
      <details className="mt-3 text-xs text-slate-600"><summary className="cursor-pointer font-medium">Statistika regresije in razlage</summary><p className="my-3 leading-relaxed">OLS: minute = prestreznik + naklon × vrstice. Sxx = Σ(x − povp. x)²; Syy = Σ(y − povp. y)²; Sxy = Σ(x − povp. x)(y − povp. y). Naklon = Sxy/Sxx; prestreznik = povp. y − naklon × povp. x; r = Sxy/√(Sxx Syy). Pri tem OLS s prestreznikom je R² = r². Opisna kovarianca = Sxy/n. Majhen vzorec ne podpira sklepa o splošni povezanosti.</p><dl className="grid grid-cols-2 gap-3 md:grid-cols-4">{[
        ['n', regression.n], ['Manjkajoči pari', regression.missing], ['Sxx (vrstice²)', regression.sxx], ['Syy (min²)', regression.syy], ['Sxy (vrstice × min)', regression.sxy], ['Kovarianca (deljeno z n)', regression.covariance], ['Vzorčna kovarianca (n − 1)', regression.sampleCovariance], ['Naklon (min/vrstico)', regression.slope], ['Prestreznik (min)', regression.intercept], ['Pearson r', regression.r], ['R²', regression.rSquared]
      ].map(([name, value]) => <div key={String(name)}><dt className="text-slate-500">{name}</dt><dd className="font-semibold text-slate-900">{numeric(value as number | null, 4)}</dd></div>)}</dl>{regression.reason && <p className="mt-3 text-amber-800">{regression.reason}</p>}</details>
      <StatisticsDrawer statistics={data.workload.preparationStatistics} unit="minute" />
    </BusinessChart>
    {residuals && <BusinessChart title="Ostanki regresije" description="Opazovane minute minus OLS ocena. Enaki pari kot v regresiji." data={[{ type: 'scatter', mode: 'markers', x: paired.map(point => point.x), y: paired.map(point => regression.slope == null || regression.intercept == null ? null : point.y - regression.intercept - regression.slope * point.x), customdata: paired.map(point => drillData(point.id)) }]} xTitle="Različne vrstice" yTitle="Ostanek (minute)" columns={['Naročilo', 'Vrstice', 'Ostanek (minute)']} rows={paired.map(point => ({ values: [point.label, point.x, regression.slope == null || regression.intercept == null ? null : point.y - regression.intercept - regression.slope * point.x], href: point.href }))} onDrill={onDrill} empty={regression.slope == null} />}
    {!workloadOnly && <>
      <div className="flex flex-wrap items-center gap-3 text-xs"><label className="flex items-center gap-2"><input type="checkbox" checked={logarithmic} onChange={event => setLogarithmic(event.target.checked)} />Logaritemska os vrednosti</label><label className="flex items-center gap-2">Izbrano naročilo za z-vrednost<select className={control + ' max-w-52'} value={selectedId} onChange={event => setSelectedId(event.target.value)}><option value="">Izberite prikazano naročilo</option>{data.laboratory.points.map(point => <option key={point.id} value={point.id}>{point.label}</option>)}</select></label></div>
      <BusinessChart title="Vrednost naročil skozi čas" description={`Oddana naročila: n = ${data.laboratory.total}; narisanih ${labPoints.length}. Pozitivnih: ${data.laboratory.positiveCount}; ničelnih/negativnih: ${data.laboratory.nonPositiveCount}${logarithmic ? ' (izključena z logaritemske osi)' : ''}. Logaritemska os sama ne dokazuje lognormalnosti ali eksponentne rasti.`} data={Array.from(new Set(labPoints.map(point => point[groupBy]))).map((group, index) => ({ type: 'scatter', mode: 'markers', name: groupBy === 'source' ? group === 'quote' ? 'Iz ponudbe' : 'Neposredno' : group === 'unknown' ? 'Neznano' : getCustomerTypeLabel(group), x: labPoints.filter(point => point[groupBy] === group).map(point => new Intl.DateTimeFormat('sv-SE', { timeZone: 'Europe/Ljubljana', year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', second: '2-digit', hourCycle: 'h23' }).format(new Date(point.x)).replace(' ', 'T')), y: labPoints.filter(point => point[groupBy] === group).map(point => point.y), text: labPoints.filter(point => point[groupBy] === group).map(point => point.label), marker: { color: palette[index % palette.length], size: labPoints.filter(point => point[groupBy] === group).map(point => point.id === selectedId ? 15 : 7), opacity: .75 }, customdata: labPoints.filter(point => point[groupBy] === group).map(point => drillData(point.id)) })) as Data[]} xTitle="Datum oddaje (Europe/Ljubljana)" yTitle="Vrednost blaga (EUR)" layout={{ xaxis: { type: 'date', tickformat: '%d.%m.%Y', title: { text: 'Datum oddaje (Europe/Ljubljana)' }, gridcolor: '#f1f5f9', automargin: true }, yaxis: { type: logarithmic ? 'log' : 'linear', title: { text: 'EUR brez DDV in poštnine' }, gridcolor: '#f1f5f9', automargin: true } }} columns={['Naročilo', 'Datum', 'Vrednost blaga (EUR)', 'Izvor', 'Tip naročnika']} rows={data.laboratory.points.map(point => ({ values: [point.label, new Intl.DateTimeFormat('sl-SI', { timeZone: 'Europe/Ljubljana', dateStyle: 'medium' }).format(new Date(point.x)), point.y, point.source === 'quote' ? 'Iz ponudbe' : 'Neposredno', point.customerType === 'unknown' ? 'Neznano' : getCustomerTypeLabel(point.customerType)], href: point.href }))} onDrill={onDrill} empty={!labPoints.length}>
        {selected && <p className="text-xs text-slate-600">{selected.label}: {eur(selected.y)} · z = (x − povprečje)/standardni odklon = <strong>{numeric(zScore(selected.y, data.orders.statistics), 3)}</strong>. Razdalja od povprečja v standardnih odklonih; sama po sebi ne določa verjetnosti normalne porazdelitve. Pri ničelnem odklonu z ni določen.</p>}<StatisticsDrawer statistics={data.orders.statistics} unit="EUR" />
      </BusinessChart>
      <div className="flex flex-wrap items-center gap-3 text-xs"><label className="flex items-center gap-2">Porazdelitev<select className={control} value={distribution} onChange={event => setDistribution(event.target.value as typeof distribution)}><option value="observed">Opazovana</option><option value="normal">Kandidat: normalna</option><option value="lognormal">Kandidat: lognormalna</option></select></label></div>
      <div className="grid gap-4 xl:grid-cols-2"><BusinessChart title="Opazovana porazdelitev in kandidatni model" description="Frekvence so opažene; gladka črta je model, ne ugotovljeno dejstvo. Vsi pasovi ohranijo dolg rep." data={distributionTraces} xTitle="Vrednost blaga (EUR)" yTitle="Naročila v pasu" columns={['Spodnja meja (EUR)', 'Zgornja meja (EUR)', 'Opazovanja']} rows={data.orders.histogram.map(bin => ({ values: [bin.min, bin.max, bin.count], drill: { kind: 'orders', min: String(bin.min), max: String(bin.max), inclusiveMax: String(bin.last) } }))} onDrill={onDrill} empty={!data.orders.histogram.length}><p className="text-xs leading-relaxed text-slate-500">{distribution === 'normal' && fit.normal ? `X ~ N(μ, σ²): μ = ${numeric(fit.normal.mean)} EUR; σ² = ${numeric(fit.normal.variance)} EUR². Drugi parameter je varianca.` : distribution === 'lognormal' && fit.lognormal ? `ln(X/EUR) ~ N(μ, σ²): μ = ${numeric(fit.lognormal.logMean)}, σ² = ${numeric(fit.lognormal.logVariance)} v logaritemskih enotah. Pozitivnih ${fit.positiveCount}; izključenih ${fit.excluded}. Aritmetična modelna sredina exp(μ + σ²/2) = ${eur(fit.lognormal.arithmeticMean)}.` : 'Najprej presodite opazovano obliko porazdelitve.'}</p></BusinessChart><BusinessChart title={distribution === 'lognormal' ? 'Normalni Q–Q na logaritemskih vrednostih' : 'Normalni Q–Q na izvirnih vrednostih'} description="Teoretični kvantili standardne normalne porazdelitve in opazovani kvantili. Odstopanje od premice pokaže odstopanje oblike od normalnosti." data={[{ type: 'scatter', mode: 'markers', x: (distribution === 'lognormal' ? fit.qqLog : fit.qqRaw).map(point => point.theoretical), y: (distribution === 'lognormal' ? fit.qqLog : fit.qqRaw).map(point => point.observed), marker: { color: '#15803d', size: 5 } }]} xTitle="Teoretični kvantil N(0,1)" yTitle={distribution === 'lognormal' ? 'ln(X/EUR)' : 'Opazovana vrednost (EUR)'} columns={['Teoretični kvantil', 'Opazovani kvantil']} rows={(distribution === 'lognormal' ? fit.qqLog : fit.qqRaw).map(point => ({ values: [point.theoretical, point.observed] }))} /></div>
      <div className={adminAnalyticsPanelClassName}><h2 className="text-sm font-semibold">Empirična porazdelitev in ponovni izračun poštnine</h2><div className="mt-3 flex flex-wrap items-center gap-3 text-xs"><select aria-label="Spremenljivka porazdelitve" className={control} value={cdfVariable} onChange={event => setCdfVariable(event.target.value as 'value' | 'weight')}><option value="value">Vrednost naročila (EUR)</option><option value="weight">Dejanska zapakirana masa (kg)</option></select><label>Prag <input className={control + ' w-24'} type="number" step="any" value={threshold} onChange={event => setThreshold(event.target.value)} /></label><strong>{percent(cdfRate)} opazovanj ≤ prag</strong>{cdfVariable === 'value' && <><label>Tarifni prag blaga z DDV (EUR) <input type="number" min={0} step={0.01} className={control + ' w-24'} value={replayThreshold} onChange={event => setReplayThreshold(event.target.value)} /></label><button type="button" className={control} disabled={replayThreshold.trim() === '' || !Number.isFinite(Number(replayThreshold)) || Number(replayThreshold) < 0} onClick={() => onChange({ thresholdCents: String(Math.round(Number(replayThreshold) * 100)) })}>Ponovi pravila s tarifnim pragom</button></>}</div><p className="mt-3 text-xs text-slate-500">Simulacija ponovno izračuna iste zgodovinske košarice po obstoječem stopenjskem pravilniku. Upošteva masne pasove, dimenzije, pakete in vrednostni popust. Ne spreminja aktivnih cen in ne napoveduje odziva povpraševanja.</p></div>
      <div className="grid gap-4 xl:grid-cols-2"><BusinessChart title="Empirična kumulativna porazdelitev" description="Delež veljavnih opazovanj pri ali pod x. Manjkajoče meritve so izključene." data={[{ type: 'scatter', mode: 'lines', x: cdf.map(point => point.value), y: cdf.map(point => point.probability * 100), line: { shape: 'hv', color: '#15803d' }, customdata: cdf.map(point => JSON.stringify({ kind: 'orders', basis: cdfVariable === 'weight' ? 'weight' : 'activity', max: String(point.value), inclusiveMax: 'true' })) }]} xTitle={cdfVariable === 'value' ? 'Vrednost (EUR)' : 'Dejanska zapakirana masa (kg)'} yTitle="Opazovanja ≤ x (%)" layout={{ shapes: Number.isFinite(thresholdValue) ? [{ type: 'line', x0: thresholdValue, x1: thresholdValue, y0: 0, y1: 100, line: { color: '#b45309', dash: 'dot' } }] : [] }} columns={['Prag', 'Delež']} rows={cdf.map(point => ({ values: [point.value, percent(point.probability)], drill: { kind: 'orders', basis: cdfVariable === 'weight' ? 'weight' : 'activity', max: String(point.value), inclusiveMax: 'true' } }))} onDrill={onDrill} empty={!cdf.length} /><BusinessChart title="Ponovni izračun zgodovinske poštnine" description={`Uporabnih košaric: ${data.shipping.replay.usable}; narisanih ${data.shipping.replay.points.length}; vsoti vključujeta vse uporabne košarice. Pravilnik ${data.shipping.replay.configurationVersion ?? 'ni na voljo'}. Zgodovinsko ${eur(data.shipping.replay.originalCharges)}; ponovni izračun ${eur(data.shipping.replay.replayCharges)}. Davčna osnova je enaka.`} data={[{ type: 'scatter', mode: 'markers', x: data.shipping.replay.points.map(point => point.original), y: data.shipping.replay.points.map(point => point.replay), customdata: data.shipping.replay.points.map(point => drillData(point.id)) }]} xTitle="Zgodovinska poštnina (EUR)" yTitle="Ponovno izračunana poštnina (EUR)" rows={data.shipping.replay.points.map(point => ({ values: [point.id, point.original, point.replay], href: point.href }))} columns={['Naročilo', 'Zgodovinsko (EUR)', 'Ponovni izračun (EUR)']} onDrill={onDrill} empty={!data.shipping.replay.usable} /></div>
      <article className={adminAnalyticsPanelClassName}><h2 className="text-sm font-semibold">Binomski scenarij · X ~ B(n, p)</h2><div className="mt-3 flex flex-wrap gap-3 text-xs"><label>Poskusov n <input type="number" min={0} max={10000} step={1} className={control + ' w-24'} value={n} onChange={event => setN(event.target.value)} /></label><label>Vir p <select className={control} value={pSource} onChange={event => setPSource(event.target.value)}><option value="mature" disabled={data.laboratory.binomialSource.rate == null}>Ponudbe ≥ 30 dni v obdobju</option><option value="scenario">Uporabniški scenarij</option></select></label>{pSource === 'scenario' && <label>p <input type="number" min={0} max={1} step={.01} className={control + ' w-24'} value={scenarioP} onChange={event => setScenarioP(event.target.value)} /></label>}<label>Vsaj k sprejemov <input type="number" min={0} max={Number(n) + 1} step={1} className={control + ' w-24'} value={k} onChange={event => setK(event.target.value)} /></label></div><p className="mt-3 text-xs leading-relaxed text-slate-500">{pSource === 'mature' ? `p iz ${data.laboratory.binomialSource.accepted}/${data.laboratory.binomialSource.total} ponudb z vsaj 30 dnevi od prve izdaje, sprejem v 30 dneh od prve izdaje v izbranem obdobju. Ocena p ima negotovost.` : 'p je uporabniška predpostavka.'} Predpostavki: neodvisni poskusi in enaka verjetnost pri vseh. Ta vstavitveni scenarij ni potrjena napoved.</p>{scenario.error && <p role="alert" className="mt-3 text-sm text-red-700">{scenario.error}</p>}{scenario.result && <p className="mt-3 text-sm text-slate-700">E[X] = np = <strong>{numeric(scenario.result.expected)}</strong> · SD = √(np(1−p)) = {numeric(scenario.result.standardDeviation)} · P(X ≥ {scenario.result.threshold}) = <strong>{percent(scenario.result.tail)}</strong></p>}</article>
      {scenario.result && <BusinessChart title="Verjetnosti binomskega scenarija" description={`n = ${scenario.result.n}, p = ${numeric(scenario.result.p, 4)}; zelena označuje X ≥ k.`} data={[{ type: 'bar', x: scenario.result.probabilities.map((_, index) => index), y: scenario.result.probabilities.map(probability => probability * 100), marker: { color: scenario.result.probabilities.map((_, index) => index >= Number(k) ? '#15803d' : '#cbd5e1') } }]} xTitle="Število sprejemov X" yTitle="Verjetnost (%)" columns={['X', 'P(X)']} rows={scenario.result.probabilities.map((probability, index) => ({ values: [index, probability] }))} />}
    </>}
  </div>;
}
