'use client';

import { useEffect, useRef, useState } from 'react';
import dynamic from 'next/dynamic';
import { useRouter, useSearchParams } from 'next/navigation';
import type { Data } from 'plotly.js';
import { BUSINESS_VIEWS, type BusinessAnalyticsResponse, type BusinessBox, type BusinessView } from '@/shared/domain/analytics/businessAnalytics';
import { BUSINESS_PERIOD_PRESETS } from '@/shared/domain/analytics/period';
import type { HistogramBin } from '@/shared/domain/analytics/statistics';
import { CUSTOMER_TYPE_FORM_OPTIONS, getCustomerTypeLabel } from '@/shared/domain/order/customerType';
import { ORDER_STATUS_OPTIONS } from '@/shared/domain/order/orderStatus';
import EuiTabs from '@/shared/ui/eui-tabs';
import AdminOrdersActivityHeatmap from '../AdminOrdersActivityHeatmap';
import BusinessChart, { DataTable, StatisticsDrawer, eur, numeric, percent, palette, downloadRows, type Drill, type TableRow } from './BusinessChart';
import BusinessRecords from './BusinessRecords';

const Geography = dynamic(() => import('./BusinessGeography'), { loading: () => <p className="p-6 text-sm text-slate-500">Nalaganje zemljevida …</p>, ssr: false });
const Laboratory = dynamic(() => import('./BusinessLaboratory'), { loading: () => <p className="p-6 text-sm text-slate-500">Nalaganje laboratorija …</p>, ssr: false });
const Measurements = dynamic(() => import('./BusinessMeasurements'), { ssr: false });
const labels: Record<BusinessView, string> = { pregled: 'Pregled', narocila: 'Naročila', ponudbe: 'Ponudbe', stranke: 'Stranke', artikli: 'Artikli', postnina: 'Poštnina', zemljevid: 'Zemljevid', laboratorij: 'Laboratorij' };
const control = 'h-8 rounded-lg border border-slate-200 bg-white px-2 text-xs text-slate-700 focus:outline-blue-600';
const dayLabel = (date: string) => new Intl.DateTimeFormat('sl-SI', { timeZone: 'UTC', day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(date + 'T12:00:00Z'));
const serializeDrill = (drill: Drill) => JSON.stringify(drill);

function Histogram({ title, bins, unit, onDrill, kind = 'orders', basis = 'activity', markers, children }: { title: string; bins: HistogramBin[]; unit: string; onDrill: (drill: Drill) => void; kind?: string; basis?: string; markers?: { mean: number | null; median: number | null; q1: number | null; q3: number | null }; children?: React.ReactNode }) {
  const visibleMarkers = markers ? { mean: markers.mean, median: markers.median, q1: markers.q1, q3: markers.q3 } : null;
  const drills = bins.map(bin => ({ kind, basis, min: String(bin.min), max: String(bin.max), inclusiveMax: String(bin.last) }));
  return <BusinessChart title={title} description={`n = ${bins.reduce((sum, bin) => sum + bin.count, 0)}. Celoten razpon s skrajnimi vrednostmi; pasovi so levo zaprti, zadnji tudi desno.`} data={[{ type: 'bar', x: bins.map(bin => (bin.min + bin.max) / 2), y: bins.map(bin => bin.count), width: bins.map(bin => bin.max === bin.min ? 1 : (bin.max - bin.min) * .94), marker: { color: '#16a34a' }, customdata: drills.map(serializeDrill) }]} layout={{ shapes: visibleMarkers ? Object.values(visibleMarkers).filter((value): value is number => value != null).map((value, index) => ({ type: 'line', x0: value, x1: value, y0: 0, y1: 1, yref: 'paper', line: { color: palette[index % palette.length], width: 1.3, dash: 'dot' } })): [], annotations: visibleMarkers ? Object.entries(visibleMarkers).filter(([, value]) => value != null).map(([key, value], index) => ({ x: value!, y: 1, yref: 'paper', text: key === 'mean' ? 'Povp.' : key === 'median' ? 'Med.' : key.toUpperCase(), showarrow: false, yshift: 8 + (index % 2) * 12, font: { size: 9, color: palette[index % palette.length] } })) : [] }} xTitle={unit} yTitle="Število opazovanj" rows={bins.map((bin, index) => ({ values: [numeric(bin.min) + ' – ' + numeric(bin.max), bin.count], drill: drills[index] }))} columns={['Razpon (' + unit + ')', 'Opazovanja']} onDrill={onDrill} empty={!bins.length}>{children}</BusinessChart>;
}

function Boxes({ title, boxes, source, onDrill }: { title: string; boxes: BusinessBox[]; source?: boolean; onDrill: (drill: Drill) => void }) {
  const traces: Data[] = [];
  boxes.forEach((box, index) => {
    if (box.q1 == null || box.q3 == null || box.median == null) return;
    const drill = serializeDrill({ kind: 'orders', [source ? 'source' : 'customerType']: box.key });
    traces.push({ type: 'scatter', mode: 'lines', name: box.label, showlegend: false, x: [index - .25, index + .25, index + .25, index - .25, index - .25], y: [box.q1, box.q1, box.q3, box.q3, box.q1], fill: 'toself', fillcolor: '#dcfce7', line: { color: '#15803d', width: 1.5 }, customdata: Array(5).fill(drill) });
    traces.push({ type: 'scatter', mode: 'lines', showlegend: false, x: [index, index, null, index - .25, index + .25], y: [box.lowerWhisker, box.upperWhisker, null, box.median, box.median], line: { color: '#15803d', width: 2 }, customdata: Array(5).fill(drill) });
    traces.push({ type: 'scatter', mode: 'markers', showlegend: false, x: box.outliers.map(() => index), y: box.outliers, marker: { size: 5, color: '#b45309' }, customdata: box.outliers.map(() => drill) });
  });
  return <BusinessChart title={title} description="Škatla Q1–Q3, črta mediana; brki do zadnjega opazovanja znotraj 1,5 × IQR. Osamelci ostanejo vidni." data={traces} yTitle="EUR brez DDV in poštnine" layout={{ xaxis: { tickvals: boxes.map((_, index) => index), ticktext: boxes.map(box => box.label + ' (n=' + box.n + ')'), zeroline: false } }} columns={['Skupina', 'n', 'Q1 (EUR)', 'Mediana (EUR)', 'Q3 (EUR)', 'Spodnji brk', 'Zgornji brk', 'Osamelci']} rows={boxes.map(box => ({ values: [box.label, box.n, box.q1, box.median, box.q3, box.lowerWhisker, box.upperWhisker, box.outliers.join(', ')], drill: { kind: 'orders', [source ? 'source' : 'customerType']: box.key } }))} onDrill={onDrill} empty={!traces.length} />;
}

export default function BusinessDashboard() {
  const router = useRouter(); const search = useSearchParams(); const query = search.toString();
  const view = (BUSINESS_VIEWS as readonly string[]).includes(search.get('view') ?? '') ? search.get('view') as BusinessView : 'pregled';
  const navigation = useRef<HTMLDivElement>(null);
  useEffect(() => {
    const revealSelection = () => {
      const container = navigation.current;
      const selected = container?.querySelector('[aria-selected="true"]');
      if (!container || !selected) return;
      const outer = container.getBoundingClientRect(), inner = selected.getBoundingClientRect();
      if (inner.left < outer.left) container.scrollLeft -= outer.left - inner.left;
      else if (inner.right > outer.right) container.scrollLeft += inner.right - outer.right;
    };
    revealSelection();
    window.addEventListener('resize', revealSelection);
    return () => window.removeEventListener('resize', revealSelection);
  }, [view]);
  const range = search.get('range') ?? '90D';
  const [data, setData] = useState<BusinessAnalyticsResponse | null>(null);
  const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [reload, setReload] = useState(0); const [drill, setDrill] = useState<Drill | null>(null);
  const [customFrom, setCustomFrom] = useState(search.get('from') ?? '');
  const [customTo, setCustomTo] = useState(search.get('to') ?? '');
  const [capture, setCapture] = useState(false);
  const update = (changes: Record<string, string | null>) => {
    const params = new URLSearchParams(query);
    Object.entries(changes).forEach(([key, value]) => value == null ? params.delete(key) : params.set(key, value));
    setDrill(null); router.replace('/admin/analitika?' + params.toString(), { scroll: false });
  };
  useEffect(() => {
    const controller = new AbortController(); setLoading(true); setError('');
    fetch('/api/admin/analytics/business?' + query, { signal: controller.signal, cache: 'no-store' }).then(async response => {
      const payload = await response.json(); if (!response.ok) throw new Error(payload.message ?? 'Analitika trenutno ni na voljo.'); return payload as BusinessAnalyticsResponse;
    }).then(payload => { if (!controller.signal.aborted) setData(payload); }).catch(error => { if (error.name !== 'AbortError') { setError(error.message); setData(null); } }).finally(() => { if (!controller.signal.aborted) setLoading(false); });
    return () => controller.abort();
  }, [query, reload]);
  const frozenParams = new URLSearchParams(query);
  if (data) frozenParams.set('asOf', data.asOf);
  const frozenQuery = frozenParams.toString();
  const select = (next: Drill) => setDrill(next);
  const goto = (next: BusinessView) => update({ view: next });
  const orderExport = '/api/admin/analytics/business/records?' + frozenQuery + '&kind=orders&format=csv';
  const trends = (value: boolean) => {
    if (!data) return null;
    const daily = data.days;
    return <BusinessChart title={value ? 'Vrednost oddanih naročil' : 'Oddana naročila'} description={`${dayLabel(data.period.from)}–${dayLabel(data.period.to)} · ${data.period.comparison.label}. Črtkana: prejšnje obdobje; drseče povprečje: 7 lokalnih koledarskih dni.`} data={[
      { type: 'scatter', mode: 'lines', name: 'Izbrano obdobje', x: daily.map(day => day.date), y: daily.map(day => !day.available ? null : value ? day.valueCount === day.orderCount ? day.activityValue : null : day.orderCount), line: { color: '#15803d', width: 2 }, customdata: daily.map(day => serializeDrill({ kind: 'orders', date: day.date })), connectgaps: false },
      { type: 'scatter', mode: 'lines', name: 'Prejšnje obdobje', x: daily.map(day => day.date), y: daily.map(day => value ? day.previousValue : day.previousCount), line: { color: '#94a3b8', width: 1.3, dash: 'dot' }, hoverinfo: 'y' },
      { type: 'scatter', mode: 'lines', name: '7-dnevno povprečje', x: daily.map(day => day.date), y: daily.map(day => value ? day.rollingValue7 : day.rollingCount7), line: { color: '#2563eb', width: 1 }, connectgaps: false }
    ]} layout={{ xaxis: { type: 'date', tickvals: daily.filter((_, index) => index % Math.max(1, Math.ceil(daily.length / 5)) === 0).map(day => day.date), ticktext: daily.filter((_, index) => index % Math.max(1, Math.ceil(daily.length / 5)) === 0).map(day => dayLabel(day.date)), gridcolor: '#f1f5f9', automargin: true } }} xTitle="Datum (Europe/Ljubljana)" yTitle={value ? 'EUR brez DDV in poštnine' : 'Naročila'} rows={daily.map(day => ({ values: [day.date + (day.partial ? ' (delno)' : ''), day.available ? value ? day.valueCount === day.orderCount ? day.activityValue : null : day.orderCount : null, value ? day.previousValue : day.previousCount, day.previousDate], drill: { kind: 'orders', date: day.date } }))} columns={['Datum', value ? 'Vrednost (EUR)' : 'Naročila', 'Prejšnje obdobje', 'Primerjalni datum']} onDrill={select} empty={!daily.some(day => day.available)} />;
  };
  const concentration = (compact: boolean) => {
    if (!data) return null;
    const customers = compact ? data.customers.customers.slice(0, 10) : data.customers.customers;
    return <BusinessChart title="Koncentracija naročnikov" description={`Realizirano blago pred vračili, brez DDV in poštnine. Top 5: ${percent(data.customers.top5Share)} · top 10: ${percent(data.customers.top10Share)}. Brez povezane identitete: ${data.customers.unlinkedOrders} naročil.`} data={[{ type: 'bar', x: customers.map((_, index) => index + 1), y: customers.map(customer => customer.value), text: customers.map(customer => customer.label), textposition: 'none', hovertemplate: '%{text}<br>%{y:.2f} EUR<extra></extra>', customdata: customers.map(customer => serializeDrill({ kind: 'orders', basis: 'lorenz', customerKey: customer.key })), marker: { color: '#15803d' } }]} xTitle="Naročniki po vrednosti (rang)" yTitle="EUR pred vračili" columns={['Naročnik', 'Vrednost pred vračili (EUR)', 'Po vračilih (EUR)', 'Naročila', 'Kumulativni delež']} rows={customers.map(customer => ({ values: [customer.label, customer.value, customer.netValue, customer.orders, percent(customer.cumulativeShare)], drill: { kind: 'orders', basis: 'lorenz', customerKey: customer.key } }))} onDrill={select} empty={!customers.length}>{compact && <button type="button" className="mt-2 text-xs text-blue-700 underline" onClick={() => goto('stranke')}>Vse stranke in Lorenzova krivulja →</button>}</BusinessChart>;
  };
  return <section className="space-y-4" aria-label="Poslovna analitika">
    <div className="rounded-xl border border-slate-200 bg-white px-4 py-3">
      <div className="flex flex-wrap items-center justify-between gap-3"><div className="flex flex-wrap gap-1" aria-label="Obdobje">{BUSINESS_PERIOD_PRESETS.map(preset => <button key={preset} type="button" onClick={() => update({ range: preset, from: null, to: null })} aria-pressed={range.toUpperCase() === preset} className={`h-8 rounded-lg px-3 text-xs font-semibold ${range.toUpperCase() === preset ? 'bg-slate-900 text-white' : 'bg-slate-50 text-slate-600 hover:bg-slate-100'}`}>{preset}</button>)}<button type="button" className={`h-8 rounded-lg px-3 text-xs ${range === 'custom' ? 'bg-slate-900 text-white' : 'text-slate-500'}`} onClick={() => { setCustomFrom(data?.period.from ?? ''); setCustomTo(data?.period.to ?? ''); update({ range: 'custom', from: data?.period.from ?? '', to: data?.period.to ?? '' }); }}>Po meri</button></div><a href={orderExport} className="text-xs text-blue-700 underline">Izvoz naročil CSV</a></div>
      <div className="mt-3 flex flex-wrap items-end gap-3">
        <label className="grid gap-1 text-[10px] font-medium uppercase tracking-wide text-slate-500">Tip naročnika<select className={control} value={search.get('customerType') ?? 'all'} onChange={event => update({ customerType: event.target.value })}><option value="all">Vsi</option>{CUSTOMER_TYPE_FORM_OPTIONS.map(option => <option key={option.value} value={option.value}>{option.label}</option>)}<option value="unknown">Neznano</option></select></label>
        <label className="grid gap-1 text-[10px] font-medium uppercase tracking-wide text-slate-500">Status naročila<select className={control} value={search.get('status') ?? 'all'} onChange={event => update({ status: event.target.value })}><option value="all">Vsi statusi</option>{ORDER_STATUS_OPTIONS.map(option => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label>
        <label className="grid gap-1 text-[10px] font-medium uppercase tracking-wide text-slate-500">Izvor naročila<select className={control} value={search.get('source') ?? 'all'} onChange={event => update({ source: event.target.value })}><option value="all">Vsi izvori</option><option value="direct">Neposredno</option><option value="quote">Iz ponudbe</option></select></label>
        {range === 'custom' && <form className="flex flex-wrap items-end gap-2" onSubmit={event => { event.preventDefault(); update({ from: customFrom, to: customTo }); }}><label className="grid gap-1 text-[10px] text-slate-500">Od<input required type="date" className={control} value={customFrom} onChange={event => setCustomFrom(event.target.value)} /></label><label className="grid gap-1 text-[10px] text-slate-500">Do (vključeno)<input required type="date" className={control} value={customTo} onChange={event => setCustomTo(event.target.value)} /></label><button className={control}>Uporabi</button></form>}
        {data && <p title={`${data.period.start} ≤ čas < ${data.period.endExclusive}; prejšnje: ${data.period.comparison.start}–${data.period.comparison.endExclusive}`} className="ml-auto text-right text-[11px] leading-relaxed text-slate-500">{dayLabel(data.period.from)} – {dayLabel(data.period.to)}<br />Europe/Ljubljana{data.period.partialToday ? ' · danes delno' : ''}</p>}
      </div>
    </div>
    {search.get('legacyRange') && <p className="text-xs text-slate-500">Stara povezava je odprla poslovno analitiko s privzetim obdobjem 90D. Obdobje spremenite v skupnih filtrih.</p>}<div ref={navigation} className="overflow-x-auto"><EuiTabs ariaLabel="Poslovni pogledi" variant="secondary" className="min-w-max" value={view} onChange={next => goto(next as BusinessView)} tabs={BUSINESS_VIEWS.map(key => ({ value: key, label: labels[key] }))} /></div>
    {loading ? <div role="status" className="rounded-xl border border-slate-200 bg-white p-8 text-sm text-slate-500">Nalaganje analitike za izbrane filtre …</div> : error ? <div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-5 text-sm text-red-800">{error}<button type="button" className="ml-3 underline" onClick={() => setReload(reload + 1)}>Poskusi znova</button></div> : data && <>
      {(view === 'pregled' || view === 'narocila') && <>
        {view === 'pregled' && <div className="grid grid-cols-2 gap-3 xl:grid-cols-5">{[
          { label: 'Oddana naročila', value: numeric(data.summary.orderCount, 0), population: 'Po datumu oddaje · tudi preklicana', detail: { kind: 'orders' } },
          { label: 'Vrednost realiziranih naročil', value: data.summary.realisedCount === 0 ? 'Ni opazovanj' : eur(data.summary.realisedValue), population: `Po datumu realizacije · n = ${data.summary.realisedCount} · neto po vračilih`, detail: { kind: 'orders', basis: 'realised' } },
          { label: 'Povprečno oddano naročilo', value: data.summary.orderCount === 0 ? 'Ni opazovanj' : eur(data.summary.meanOrderValue), population: `Po oddaji · blago brez DDV · n = ${data.coverage.valueOrders}`, detail: { kind: 'orders' } },
          { label: 'Mediana oddanega naročila', value: data.summary.orderCount === 0 ? 'Ni opazovanj' : eur(data.summary.medianOrderValue), population: `Po oddaji · blago brez DDV · n = ${data.coverage.valueOrders}`, detail: { kind: 'orders' } },
          { label: 'Sprejem ponudb v 30 dneh', value: percent(data.summary.quoteAcceptance.rate), population: `Prva izdaja v obdobju · zreli: ${data.summary.quoteAcceptance.accepted}/${data.summary.quoteAcceptance.total}`, detail: { kind: 'quotes', basis: 'mature' } }
        ].map(card => <button type="button" key={card.label} onClick={() => select(card.detail as Drill)} className="rounded-xl border border-slate-200 bg-white p-4 text-left transition hover:border-green-600"><p className="text-[11px] font-medium text-slate-500">{card.label}</p><p className="mt-2 truncate text-[23px] font-semibold tracking-tight text-slate-950">{card.value}</p><p className="mt-2 text-[10px] leading-relaxed text-slate-500">{card.population}<br />{dayLabel(data.period.from)} – {dayLabel(data.period.to)}</p></button>)}</div>}
        <AdminOrdersActivityHeatmap days={data.days.map(day => ({ date: day.date, order_count: day.available ? day.orderCount : null, revenue_total: day.available && day.valueCount === day.orderCount ? day.activityValue : null, available: day.available, partial: day.partial }))} onSelectDay={date => select({ kind: 'orders', date })} exportHref={orderExport} />
        <div className="grid gap-4 xl:grid-cols-2">{trends(false)}{trends(true)}</div>
        {view === 'pregled' ? <div className="grid gap-4 xl:grid-cols-2"><Geography query={frozenQuery} compact onOpen={() => goto('zemljevid')} onDrill={select} />{concentration(true)}</div> : <>
          <details className="text-xs text-slate-600"><summary className="cursor-pointer">Napredne nastavitve histogramov</summary><label className="mt-2 flex items-center gap-2">Število enako širokih pasov<input type="number" min={1} max={100} defaultValue={search.get('bins') ?? '12'} className={control + ' w-20'} onBlur={event => update({ bins: event.target.value })} /></label></details>
          <Histogram title="Porazdelitev vrednosti oddanih naročil" markers={data.orders.statistics} bins={data.orders.histogram} unit="EUR brez DDV in poštnine" onDrill={select}><p className="text-xs text-slate-500">Povprečje {eur(data.orders.statistics.mean)} · mediana {eur(data.orders.statistics.median)} · Q1 {eur(data.orders.statistics.q1)} · Q3 {eur(data.orders.statistics.q3)}</p><StatisticsDrawer statistics={data.orders.statistics} unit="EUR" /></Histogram>
          <div className="grid gap-4 xl:grid-cols-2"><Boxes title="Vrednost po tipu naročnika" boxes={data.orders.boxes} onDrill={select} /><Boxes title="Neposredna naročila in naročila iz ponudb" boxes={data.orders.sourceBoxes} source onDrill={select} /></div>
        </>}
      </>}
      {view === 'ponudbe' && <><div className="rounded-xl border border-slate-200 bg-white p-4"><h2 className="text-base font-semibold">Sprejem v 30 dneh od prve izdaje</h2><p className="mt-2 text-sm text-slate-600"><strong className="text-2xl text-slate-950">{percent(data.quotes.mature.rate)}</strong> · {data.quotes.mature.accepted} sprejetih / {data.quotes.mature.total} zrelih priložnosti · Wilson 95 %: {percent(data.quotes.mature.lower)}–{percent(data.quotes.mature.upper)}</p><p className="mt-2 text-xs text-slate-500">{data.quotes.immature} še nezrelih priložnosti; {data.quotes.acceptedAfterWindow} sprejetih po 30 dneh. Revizije štejejo kot ena priložnost. Osnova pasov je prva izdana vrednost. {data.definitions.quotes}</p></div>
        <div className="grid gap-4 xl:grid-cols-2">{([{ title: 'Sprejem po začetni vrednosti ponudbe', bands: data.quotes.byValue }, { title: 'Sprejem po tipu naročnika', bands: data.quotes.byType }]).map(group => <BusinessChart key={group.title} title={group.title} description="Delež sprejetih med zrelimi priložnostmi; navpične črte so Wilsonovi 95-odstotni intervali." data={[{ type: 'scatter', mode: 'markers', x: group.bands.map(band => band.label), y: group.bands.map(band => band.rate == null ? null : band.rate * 100), error_y: { type: 'data', symmetric: false, array: group.bands.map(band => ((band.upper ?? 0) - (band.rate ?? 0)) * 100), arrayminus: group.bands.map(band => ((band.rate ?? 0) - (band.lower ?? 0)) * 100), visible: true }, marker: { size: 9, color: '#15803d' }, customdata: group.bands.map(band => serializeDrill({ kind: 'quotes', basis: 'mature', ...(band.customerType ? { customerType: band.customerType } : { min: String(band.min ?? ''), max: String(band.max ?? '') }) })) }]} yTitle="Sprejete ponudbe (%)" rows={group.bands.map(band => ({ values: [band.label, band.accepted, band.total, percent(band.rate), percent(band.lower), percent(band.upper)], href: band.href }))} columns={['Skupina', 'Sprejete', 'Zrele', 'Delež', 'Wilson spodaj', 'Wilson zgoraj']} onDrill={select} empty={!group.bands.length} />)}</div>
        <div className="grid gap-4 xl:grid-cols-2"><Histogram title="Odzivni čas Atehne" bins={data.quotes.responseHistogram} unit="ure od povpraševanja do prve izdaje" kind="quotes" basis="quote-response" onDrill={select}><StatisticsDrawer statistics={data.quotes.responseStatistics} unit="ure" /></Histogram><Histogram title="Odločitev naročnika med sprejetimi ponudbami" bins={data.quotes.decisionHistogram} unit="ure od prve izdaje do prvega sprejema" kind="quotes" basis="quote-decision" onDrill={select}><StatisticsDrawer statistics={data.quotes.decisionStatistics} unit="ure" note="Pogojno na sprejem; ne ocenjuje čakanja vseh odprtih ponudb." /></Histogram></div>
        <BusinessChart title="Opazovani deleži in kandidatni logistični model" description={data.quotes.logistic.available ? 'Logit(p) = prestreznik + naklon × začetna vrednost. Povezanost ne dokazuje vzročnosti.' : data.quotes.logistic.reason ?? 'Podatki ne zadoščajo za zanesljivo oceno; opazovani deleži zgoraj ostanejo na voljo.'} data={[{ type: 'scatter', mode: 'lines', x: data.quotes.logistic.points.map(point => point.value), y: data.quotes.logistic.points.map(point => point.probability * 100) }]} xTitle="Začetna vrednost (EUR)" yTitle="Verjetnost sprejema (%)" columns={['Začetna vrednost (EUR)', 'Modelna verjetnost']} rows={data.quotes.logistic.points.map(point => ({ values: [point.value, point.probability] }))} empty={!data.quotes.logistic.available} />
      </>}
      {view === 'stranke' && <>{concentration(false)}<div className="grid gap-4 xl:grid-cols-2"><BusinessChart title="Kumulativni delež najboljših naročnikov" description="Rang od največje do najmanjše realizirane vrednosti pred vračili." data={[{ type: 'scatter', mode: 'lines', x: data.customers.customers.map((_, index) => index + 1), y: data.customers.customers.map(customer => customer.cumulativeShare * 100), customdata: data.customers.customers.map((_, index) => serializeDrill({ kind: 'orders', basis: 'lorenz', topCustomerCount: String(index + 1) })) }]} xTitle="Število naročnikov" yTitle="Kumulativni delež (%)" columns={['Najboljših naročnikov', 'Kumulativni delež']} rows={data.customers.customers.map((customer, index) => ({ values: [index + 1, percent(customer.cumulativeShare)], drill: { kind: 'orders', basis: 'lorenz', topCustomerCount: String(index + 1) } }))} onDrill={select} /><BusinessChart title="Lorenzova krivulja" description={`Nenegativna realizirana vrednost pred vračili. Gini: ${numeric(data.customers.gini, 3)}. Anonimna naročila so izključena iz identitetnih analiz.`} data={[{ type: 'scatter', mode: 'lines', name: 'Opazovano', x: data.customers.lorenz.map(point => point.population * 100), y: data.customers.lorenz.map(point => point.share * 100), customdata: data.customers.lorenz.map(point => serializeDrill({ kind: 'orders', basis: 'lorenz', lorenzPopulation: String(point.population) })) }, { type: 'scatter', mode: 'lines', name: 'Enakomerna porazdelitev', x: [0, 100], y: [0, 100], line: { color: '#cbd5e1', dash: 'dot' } }]} xTitle="Kumulativni delež naročnikov (%)" yTitle="Kumulativni delež vrednosti (%)" columns={['Naročniki (%)', 'Vrednost (%)']} rows={data.customers.lorenz.map(point => ({ values: [point.population * 100, point.share * 100], drill: { kind: 'orders', basis: 'lorenz', lorenzPopulation: String(point.population) } }))} onDrill={select} /></div>
        <article className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="text-sm font-semibold">Ponovni nakupi po kohortah</h2><button type="button" className="text-xs text-blue-700 underline" onClick={() => downloadRows('Kohorte', ['Mesec prvega nakupa', 'Naročniki', ...Array.from({ length: data.cohorts.horizon }, (_, index) => 'M' + index)], data.cohorts.rows.map(row => ({ values: [row.month, row.customers, ...row.retention.slice(0, data.cohorts.horizon)] })))}>CSV kohort</button><select aria-label="Horizont kohort" className={control} value={search.get('horizon') ?? '24'} onChange={event => update({ horizon: event.target.value })}><option value="12">12 mesecev</option><option value="24">24 mesecev</option></select></div><p className="my-3 text-xs text-slate-500">Mesec prvega realiziranega nakupa glede na celotno razpoložljivo zgodovino. Delež izvorne kohorte, ki naroča v posameznem mesecu. {data.cohorts.historyLeftTruncated ? 'Zgodovina je levo odrezana: prvi dejanski nakup je lahko starejši.' : ''} Črtica pomeni še neopazovano obdobje; tekoči koledarski mesec je delen.</p><div className="overflow-auto"><table className="w-full text-xs"><thead><tr><th className="p-2 text-left">Prvi nakup</th><th className="px-2">n</th>{Array.from({ length: data.cohorts.horizon }, (_, index) => <th key={index} className="min-w-12 p-2">M{index}</th>)}</tr></thead><tbody>{data.cohorts.rows.map(row => <tr key={row.month}><th className="whitespace-nowrap p-2 text-left font-medium">{row.month}</th><td className="p-2">{row.customers}</td>{row.retention.slice(0, data.cohorts.horizon).map((rate, index) => <td key={index} className="border-2 border-white p-2 text-center" style={{ backgroundColor: rate == null ? '#f1f5f9' : `rgba(22,163,74,${.06 + rate * .7})` }}><button disabled={rate == null} onClick={() => select({ kind: 'orders', basis: 'realised', cohort: row.month, cohortMonth: String(index) })}>{rate == null ? '—' : percent(rate)}</button></td>)}</tr>)}</tbody></table>{!data.cohorts.rows.length && <p className="py-6 text-slate-500">Ni povezanih naročnikov z opazovano kohorto.</p>}</div></article>
      </>}
      {view === 'artikli' && <><BusinessChart title="Povpraševanje in prispevek artiklov" description={`Prodane enote in prispevek na enoto iz zgodovinske neto cene ter zabeležene nabavne cene. Pokritost stroškov: ${numeric(data.products.costCoveredUnits)}/${numeric(data.products.soldUnits)} enot. Prispevek ni čisti dobiček.`} data={Array.from(new Set(data.products.points.map(point => point.category))).map((category, index) => ({ type: 'scatter', mode: 'markers', name: category, x: data.products.points.filter(point => point.category === category && point.contributionPerUnit != null).map(point => point.units), y: data.products.points.filter(point => point.category === category && point.contributionPerUnit != null).map(point => point.contributionPerUnit), text: data.products.points.filter(point => point.category === category && point.contributionPerUnit != null).map(point => point.label), marker: { color: palette[index % palette.length], size: 9, opacity: .75 }, customdata: data.products.points.filter(point => point.category === category && point.contributionPerUnit != null).map(point => serializeDrill({ kind: 'orders', basis: 'realised', productKey: point.key })) })) as Data[]} xTitle="Prodane enote" yTitle="Prispevek na enoto (EUR)" columns={['Artikel', 'Kategorija', 'Enote', 'Enote s stroškom', 'Prispevek/enoto (EUR)', 'Naročila']} rows={data.products.points.map(point => ({ values: [point.label, point.category, point.units, point.costCoveredUnits, point.contributionPerUnit, point.orders], drill: { kind: 'orders', basis: 'realised', productKey: point.key } }))} onDrill={select} empty={!data.products.points.some(point => point.contributionPerUnit != null)} /><p className="text-xs text-slate-500">{data.definitions.costs}</p></>}
      {view === 'postnina' && <><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-xs text-slate-500">Uporabne meritve: {data.shipping.usable}/{data.shipping.total}. Nepokriti strošek: {eur(data.shipping.uncoveredCost)}. Zneski so brez DDV.</p><button className={control} onClick={() => setCapture(true)}>Vnesi dejanske meritve naročila</button></div><div className="grid gap-4 xl:grid-cols-2"><BusinessChart title="Dejanska masa in strošek prevoznika" description="Meritve zapakiranega naročila. Barva: število paketov; trikotnik: prevelik paket; prazen romb: velikostni status neznan; siva: paketi neznani. Kataloška masa ne nadomešča meritev." data={Array.from(new Set(data.shipping.points.map(point => point.parcelCount))).map((parcelCount, index) => { const points = data.shipping.points.filter(point => point.parcelCount === parcelCount); return { type: 'scatter', mode: 'markers', name: parcelCount == null ? 'Paketi: manjka podatek' : 'Paketi: ' + parcelCount, x: points.map(point => point.x), y: points.map(point => point.y), text: points.map(point => point.label), marker: { size: 9, color: parcelCount == null ? '#94a3b8' : palette[index % palette.length], symbol: points.map(point => point.oversize == null ? 'diamond-open' : point.oversize ? 'triangle-up' : 'circle') }, customdata: points.map(point => serializeDrill({ kind: 'orders', orderId: point.id })) }; }) as Data[]} xTitle="Dejanska zapakirana masa (kg)" yTitle="Prevoznik brez DDV (EUR)" columns={['Naročilo', 'Masa (kg)', 'Prevoznik neto (EUR)', 'Zaračunano neto (EUR)', 'Paketi', 'Prevelik paket']} rows={data.shipping.points.map(point => ({ values: [point.label, point.x, point.y, point.shippingChargeNet ?? null, point.parcelCount ?? null, point.oversize == null ? null : point.oversize ? 'Da' : 'Ne'], href: point.href }))} onDrill={select} empty={!data.shipping.points.length} /><BusinessChart title="Zaračunana poštnina in dejanski strošek" description={`Pokritost obeh neto zneskov: ${data.shipping.coveredCharge}. Primerjava na enaki davčni osnovi.`} data={[{ type: 'scatter', mode: 'markers', x: data.shipping.points.map(point => point.shippingChargeNet ?? null), y: data.shipping.points.map(point => point.y), customdata: data.shipping.points.map(point => serializeDrill({ kind: 'orders', orderId: point.id })) }]} xTitle="Zaračunano naročniku brez DDV (EUR)" yTitle="Prevoznik brez DDV (EUR)" columns={['Naročilo', 'Zaračunano neto (EUR)', 'Prevoznik neto (EUR)']} rows={data.shipping.points.filter(point => point.shippingChargeNet != null).map(point => ({ values: [point.label, point.shippingChargeNet!, point.y], href: point.href }))} onDrill={select} empty={!data.shipping.coveredCharge} /></div><Laboratory data={data} query={frozenQuery} onDrill={select} workloadOnly onChange={update} /></>}
      {view === 'zemljevid' && <Geography query={frozenQuery} onDrill={select} />}
      {view === 'laboratorij' && <><div className="flex justify-end"><button className={control} onClick={() => setCapture(true)}>Vnesi meritve naročila</button></div><Laboratory data={data} query={frozenQuery} onDrill={select} onChange={update} /></>}
      <details className="rounded-xl border border-slate-200 bg-white px-4 py-3 text-xs text-slate-600"><summary className="cursor-pointer font-medium">Definicije, pokritost in zgodovina podatkov</summary><div className="mt-3 space-y-2 leading-relaxed"><p>{data.definitions.activity}</p><p>{data.definitions.realised}</p><p>{data.definitions.quotes}</p><p>{data.definitions.costs}</p><p>Oddana naročila: {data.coverage.eligibleOrders}; z vrednostjo: {data.coverage.valueOrders}; ohranjen posnetek: {data.coverage.snapshotOrders}; starejši zapisi: {data.coverage.legacyOrders}. Zabeležena zgodovina od {data.coverage.historyFrom ?? 'neznanega datuma'}.</p>{data.coverage.warnings.map(warning => <p key={warning} className="text-amber-800">{warning}</p>)}<p>Skupni čas izračuna: {new Intl.DateTimeFormat('sl-SI', { timeZone: 'Europe/Ljubljana', dateStyle: 'medium', timeStyle: 'medium' }).format(new Date(data.asOf))}.</p></div></details>
    </>}
    {drill && <BusinessRecords key={JSON.stringify(drill)} query={frozenQuery} drill={drill} onClose={() => setDrill(null)} />}
    {capture && <Measurements onClose={() => setCapture(false)} onSaved={() => { setCapture(false); setReload(reload + 1); }} />}
  </section>;
}
