'use client';

import { adminAnalyticsControlClassName, adminAnalyticsPanelClassName } from '@/shared/ui/theme/tokens';

import { useEffect, useMemo, useRef, useState } from 'react';
import type { GeographyFeature, GeographyReference, Position } from '@/shared/domain/analytics/geography';
import type { BusinessRecord } from '@/shared/domain/analytics/businessAnalytics';
import { DataTable, downloadRows, eur, numeric, percent, type Drill } from './BusinessChart';
type Area = { id: string; code: string; name: string; level: 'municipality' | 'region'; regionId: string | null; orderCount: number; activityValue: number | null; knownValueOrders: number; distinctCustomers: number; mappedShare: number | null; municipalityResolvedOrders: number; regionOnlyOrders: number };
type GeoResponse = {
  asOf: string; reference: { metadata: GeographyReference['metadata']; assetUrl: string; latestVersion: string | null; lastError: string | null };
  areas: Area[]; reconciliation: { allEligibleOrders: number; mappedSlovenianOrders: number; unresolvedSlovenianOrders: number; foreignOrders: number; unknownCountryOrders: number; regionOnlyResolvedOrders: number };
  coverage: { resolvedOrders: number; missingReferenceGeometry: number; staleAddressResolutions: number; otherVintageOrders: number; unlinkedCustomerOrders: number };
  unresolved: { id: string; number: string; status: string; method: string; href: string }[];
  addressSource: { imported_at: string | null; source_updated_at: string | null; total: number; linked: number } | null;
  denominator: string; selected: { id: string; total: number; records: BusinessRecord[] } | null;
};
const colors = ['#e2e8f0', '#dcfce7', '#bbf7d0', '#86efac', '#4ade80', '#15803d'];
const control = adminAnalyticsControlClassName;
const normalize = (value: string) => value.normalize('NFD').replace(/\p{M}/gu, '').toLocaleLowerCase('sl');
const project = ([longitude, latitude]: Position): Position => [longitude * Math.cos(46 * Math.PI / 180), -latitude];
function pathFor(feature: GeographyFeature) {
  const polygons = feature.geometry.type === 'Polygon' ? [feature.geometry.coordinates] : feature.geometry.coordinates;
  return polygons.map(polygon => polygon.map(ring => ring.map((point, index) => (index ? 'L' : 'M') + project(point).join(',')).join(' ') + ' Z').join(' ')).join(' ');
}
export default function BusinessGeography({ query, compact = false, onOpen, onDrill }: { query: string; compact?: boolean; onOpen?: () => void; onDrill: (drill: Drill) => void }) {
  const [level, setLevel] = useState<'municipality' | 'region'>('municipality');
  const [metric, setMetric] = useState<'orders' | 'value'>('orders');
  const [scale, setScale] = useState<'linear' | 'sqrt'>('linear');
  const [data, setData] = useState<GeoResponse | null>(null); const [geometry, setGeometry] = useState<GeographyReference | null>(null);
  const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [revision, setRevision] = useState(0);
  const [selectedId, setSelectedId] = useState(''); const [hoverId, setHoverId] = useState('');
  const [search, setSearch] = useState(''); const [sort, setSort] = useState<'name' | 'orders' | 'value'>('orders');
  const [zoom, setZoom] = useState(1); const [pan, setPan] = useState({ x: 0, y: 0 });
  const [correctionOrder, setCorrectionOrder] = useState(''); const [correctionArea, setCorrectionArea] = useState('');
  const [reason, setReason] = useState(''); const [operation, setOperation] = useState(''); const [auditRows, setAuditRows] = useState<Array<Record<string, string | null>>>([]); const [pending, setPending] = useState(false);
  const svg = useRef<SVGSVGElement>(null); const drag = useRef<{ x: number; y: number; panX: number; panY: number; moved: boolean } | null>(null);
  const dragged = useRef(false);
  const params = new URLSearchParams(query); params.set('level', level); if (selectedId) params.set('area', selectedId); else params.delete('area');
  const requestKey = params.toString();
  useEffect(() => {
    const controller = new AbortController(); setLoading(true); setError('');
    fetch('/api/admin/analytics/geography?' + requestKey, { signal: controller.signal, cache: 'no-store' }).then(async response => { const payload = await response.json(); if (!response.ok) throw new Error(payload.message ?? 'Zemljevida ni mogoče naložiti.'); return payload as GeoResponse; }).then(async payload => {
      const boundaryResponse = await fetch(payload.reference.assetUrl + '?version=' + encodeURIComponent(payload.reference.metadata.version), { signal: controller.signal }); if (!boundaryResponse.ok) throw new Error('Uradne geometrije trenutno ni mogoče naložiti.');
      const boundaries = await boundaryResponse.json() as GeographyReference;
      if (boundaries.metadata.version !== payload.reference.metadata.version) throw new Error('Različici geometrije in pripisa naročil se ne ujemata.');
      if (!controller.signal.aborted) { setData(payload); setGeometry(boundaries); }
    }).catch(error => { if (error.name !== 'AbortError') { setError(error.message); setData(null); } }).finally(() => { if (!controller.signal.aborted) setLoading(false); });
    return () => controller.abort();
  }, [requestKey, revision]);
  const features = useMemo(() => geometry?.features.filter(feature => feature.properties.level === level) ?? [], [geometry, level]);
  const paths = useMemo(() => features.map(feature => ({ feature, path: pathFor(feature) })), [features]);
  const bounds = useMemo(() => {
    const coordinates = features.flatMap(feature => (feature.geometry.type === 'Polygon' ? [feature.geometry.coordinates] : feature.geometry.coordinates).flatMap(polygon => polygon.flatMap(ring => ring.map(project))));
    if (!coordinates.length) return { x: 0, y: 0, width: 2, height: 1 };
    let x = Infinity, y = Infinity, right = -Infinity, bottom = -Infinity;
    coordinates.forEach(point => { x = Math.min(x, point[0]); y = Math.min(y, point[1]); right = Math.max(right, point[0]); bottom = Math.max(bottom, point[1]); });
    const padding = (right - x) * .025; return { x: x - padding, y: y - padding, width: right - x + padding * 2, height: bottom - y + padding * 2 };
  }, [features]);
  const byId = useMemo(() => new Map(data?.areas.map(area => [area.id, area]) ?? []), [data]);
  const metricValue = (area: Area) => metric === 'orders' ? area.orderCount : area.activityValue;
  const maximum = Math.max(0, ...(data?.areas.filter(area => area.level === level).map(area => metricValue(area) ?? 0) ?? []));
  const singleValue = new Set((data?.areas.filter(area => area.level === level).map(area => metricValue(area)).filter(value => value != null && value > 0) ?? [])).size === 1;
  const thresholds = maximum > 0 ? singleValue ? [maximum] : Array.from({ length: 5 }, (_, index) => maximum * (scale === 'sqrt' ? ((index + 1) / 5) ** 2 : (index + 1) / 5)) : [];
  const fill = (area: Area | undefined) => {
    if (!area) return 'url(#geography-missing)';
    const value = metricValue(area); if (value == null || (metric === 'value' && area.knownValueOrders < area.orderCount)) return 'url(#geography-missing)';
    if (value <= 0 || !maximum) return colors[0];
    return colors[Math.min(5, Math.max(1, Math.ceil((scale === 'sqrt' ? Math.sqrt(value / maximum) : value / maximum) * 5)))];
  };
  const focusArea = byId.get(hoverId || selectedId);
  const areas = [...(data?.areas ?? [])].filter(area => area.level === level).filter(area => normalize(area.name).includes(normalize(search))).sort((left, right) => sort === 'name' ? left.name.localeCompare(right.name, 'sl') : sort === 'orders' ? right.orderCount - left.orderCount : (right.activityValue ?? -Infinity) - (left.activityValue ?? -Infinity));
  const box = { x: bounds.x + bounds.width * (1 - 1 / zoom) / 2 + pan.x, y: bounds.y + bounds.height * (1 - 1 / zoom) / 2 + pan.y, width: bounds.width / zoom, height: bounds.height / zoom };
  const selectArea = (id: string) => { if (!dragged.current) setSelectedId(selectedId === id ? '' : id); };
  const matchingLink = '/admin/orders?analytics=1&' + requestKey + '&' + (level === 'municipality' ? 'municipalityId=' : 'regionId=') + encodeURIComponent(selectedId);
  const tableRows = areas.map(area => ({ values: [area.name, area.code, area.orderCount, area.activityValue, area.distinctCustomers, percent(area.mappedShare)], drill: { kind: 'orders', [level === 'municipality' ? 'municipalityId' : 'regionId']: area.id } }));
  const loadAudit = async () => { try { const response = await fetch('/api/admin/analytics/geography/audit' + (correctionOrder ? '?orderId=' + encodeURIComponent(correctionOrder) : ''), { cache: 'no-store' }); if (!response.ok) throw new Error('Revizijske sledi ni mogoče naložiti.'); const payload = await response.json(); setAuditRows(payload.audit); } catch (error) { setOperation(error instanceof Error ? error.message : 'Napaka pri revizijski sledi.'); } };
  const mutate = async (remove: boolean, backfill = false) => {
    setPending(true); setOperation('');
    try {
      const response = await fetch('/api/admin/analytics/geography', { method: backfill ? 'POST' : 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify(backfill ? { retryUnresolved: true } : { orderId: correctionOrder, ...(level === 'municipality' ? { municipalityId: correctionArea } : { regionId: correctionArea }), reason, remove }) });
      const result = await response.json(); if (!response.ok) throw new Error(result.message ?? 'Spremembe ni bilo mogoče shraniti.');
      setOperation(backfill ? 'Serija obdelana. Večje zgodovine nadaljujte z ukazom za paketni pripis; napredek je shranjen.' : 'Popravek je shranjen v revizijski sledi.'); setRevision(value => value + 1);
    } catch (error) { setOperation(error instanceof Error ? error.message : 'Napaka pri shranjevanju.'); } finally { setPending(false); }
  };
  return <article className={adminAnalyticsPanelClassName}>
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-sm font-semibold text-slate-950">Naročila po Sloveniji</h2><p className="mt-1 text-[11px] text-slate-500">Uradne meje GURS · shranjeni naslov naročnika · ista oddana naročila kot v koledarju.</p></div>{compact && <button type="button" className="text-xs text-blue-700 underline" onClick={onOpen}>Celoten zemljevid →</button>}</div>
    <div className="mt-3 flex flex-wrap gap-2"><select aria-label="Geografska raven" className={control} value={level} onChange={event => { setLevel(event.target.value as typeof level); setSelectedId(''); setHoverId(''); setZoom(1); setPan({ x: 0, y: 0 }); }}><option value="municipality">Občine</option><option value="region">Statistične regije</option></select><select aria-label="Mera zemljevida" className={control} value={metric} onChange={event => setMetric(event.target.value as typeof metric)}><option value="orders">Naročila</option><option value="value">Vrednost naročil</option></select>{!compact && <select aria-label="Barvna lestvica" className={control} value={scale} onChange={event => setScale(event.target.value as typeof scale)}><option value="linear">Linearna lestvica</option><option value="sqrt">Kvadratni koren intenzivnosti</option></select>}</div>
    {error ? <p role="alert" className="my-6 text-sm text-red-700">{error}<button className="ml-2 underline" onClick={() => setRevision(revision + 1)}>Ponovi</button></p> : !data || !geometry ? <p role="status" className="py-20 text-center text-sm text-slate-500">Nalaganje uradnih meja in geografskih agregatov …</p> : <>
      <div className="relative mt-3 rounded-lg bg-slate-50/60" aria-busy={loading}>
        <svg ref={svg} viewBox={`${box.x} ${box.y} ${box.width} ${box.height}`} className={compact ? 'h-60 w-full touch-none' : 'h-60 w-full touch-none sm:h-[410px]'} aria-label={`Slovenija: ${level === 'municipality' ? 'občine' : 'statistične regije'}. Izberite območje ali uporabite dostopno tabelo.`} onPointerDown={event => { dragged.current = false; drag.current = { x: event.clientX, y: event.clientY, panX: pan.x, panY: pan.y, moved: false }; }} onPointerMove={event => { const start = drag.current; const rect = svg.current?.getBoundingClientRect(); if (!start || !rect) return; const dx = event.clientX - start.x, dy = event.clientY - start.y; if (Math.abs(dx) + Math.abs(dy) > 4) { start.moved = true; dragged.current = true; setPan({ x: start.panX - dx / rect.width * box.width, y: start.panY - dy / rect.height * box.height }); } }} onPointerUp={() => { drag.current = null; }} onPointerCancel={() => { drag.current = null; }}>
          <defs><pattern id="geography-missing" width=".01" height=".01" patternUnits="userSpaceOnUse"><rect width=".01" height=".01" fill="#e2e8f0" /><path d="M0,0L.01,.01" stroke="#94a3b8" strokeWidth=".002" /></pattern></defs>
          {paths.map(({ feature, path }) => {
            const area = byId.get(feature.properties.id); const selected = selectedId === feature.properties.id;
            return <path key={feature.properties.id} d={path} fill={fill(area)} fillRule="evenodd" stroke={selected ? '#0f172a' : '#ffffff'} strokeWidth={selected ? 1.8 : .7} vectorEffect="non-scaling-stroke" role="button" tabIndex={0} aria-pressed={selected} aria-label={`${feature.properties.name}, koda ${feature.properties.code}: ${area ? area.orderCount + ' naročil' : 'geometrija brez agregata'}`} className="cursor-pointer outline-none focus:stroke-slate-900 focus:stroke-[2]" onPointerEnter={() => setHoverId(feature.properties.id)} onPointerLeave={() => setHoverId('')} onFocus={() => setHoverId(feature.properties.id)} onBlur={() => setHoverId('')} onClick={() => selectArea(feature.properties.id)} onKeyDown={event => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); setSelectedId(selected ? '' : feature.properties.id); } }}><title>{feature.properties.name} · {area?.orderCount ?? '—'} naročil · {eur(area?.activityValue)}</title></path>;
          })}
        </svg>
        <div className="absolute bottom-2 right-2 flex gap-1"><button aria-label="Povečaj zemljevid" className={control} onClick={() => setZoom(Math.min(12, zoom * 1.5))}>+</button><button aria-label="Pomanjšaj zemljevid" className={control} onClick={() => setZoom(Math.max(1, zoom / 1.5))}>−</button><button className={control} onClick={() => { setZoom(1); setPan({ x: 0, y: 0 }); }}>Cela Slovenija</button></div>
      </div>
      <div className="mt-3 flex flex-wrap gap-x-3 gap-y-2 text-[10px] text-slate-500"><span>0 {metric === 'orders' ? 'naročil' : 'EUR'}</span>{thresholds.map((threshold, index) => <span key={index} className="inline-flex items-center gap-1"><i className="h-3 w-3 rounded-sm" style={{ background: colors[singleValue ? 5 : index + 1] }} />≤ {numeric(threshold)} {metric === 'orders' ? 'naročil' : 'EUR'}</span>)}<span>Šrafura: nerazpoložljivo</span>{!thresholds.length && <span>Vsa razpoložljiva območja imajo vrednost 0.</span>}</div>
      <div className="mt-3 min-h-12 text-xs text-slate-600" aria-live="polite">{focusArea ? <><strong>{focusArea.name}</strong> · uradna koda {focusArea.code} · {focusArea.orderCount} naročil · {eur(focusArea.activityValue)} blaga brez DDV/poštnine · {focusArea.distinctCustomers} povezanih naročnikov · {percent(focusArea.mappedShare)} preslikanih slovenskih naročil<p className="mt-1 text-[10px] text-slate-500">Imenovalec: {data.denominator}</p></> : 'Izberite območje za podrobnosti. Prikazana koda je nacionalna šifra; povezave uporabljajo uradni EID.'}</div>
      <p className="mt-2 text-[11px] leading-relaxed text-slate-500">{data.reconciliation.mappedSlovenianOrders} preslikanih slovenskih + {data.reconciliation.unresolvedSlovenianOrders} nerazrešenih slovenskih + {data.reconciliation.foreignOrders} tujih + {data.reconciliation.unknownCountryOrders} z neznano državo = <strong>{data.reconciliation.allEligibleOrders} vseh upravičenih naročil</strong>. {data.reconciliation.unresolvedSlovenianOrders > 0 ? 'Ničla na območju ne pomeni popolnega pripisa vseh naslovov.' : ''}{data.reconciliation.regionOnlyResolvedOrders > 0 ? ` Samo regija: ${data.reconciliation.regionOnlyResolvedOrders}; enakost vsote občin in regij velja za skupno občinsko razrešeno podmnožico.` : ''}</p>
      {data.coverage.missingReferenceGeometry > 0 && <p role="alert" className="mt-2 text-xs text-red-700">Napaka izrisa: {data.coverage.missingReferenceGeometry} zapisov nima geometrije izbrane različice. Zapisi ostajajo v uskladitvi.</p>}
      {!compact && <>
        {selectedId && <section className="mt-4 rounded-lg border border-green-200 bg-green-50/30 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="text-sm font-semibold">{byId.get(selectedId)?.name} · {data.selected?.total ?? 0} naročil</h3><button className="text-xs text-blue-700 underline" onClick={() => setSelectedId('')}>Počisti izbor</button></div><p className="mt-1 text-[11px] text-slate-500">Izbor velja samo v zemljevidu.</p><DataTable columns={['Naročilo', 'Datum', 'Naročnik', 'Vrednost (EUR)']} rows={data.selected?.records.map(record => ({ values: [record.number, new Intl.DateTimeFormat('sl-SI', { timeZone: 'Europe/Ljubljana', dateStyle: 'medium' }).format(new Date(record.date)), record.customerName, record.value], href: record.href })) ?? []} /><div className="mt-3 flex flex-wrap gap-3 text-xs text-blue-700"><a className="underline" href={matchingLink}>Odpri pripadajoči seznam naročil</a><a className="underline" href={'/api/admin/analytics/geography?' + requestKey + '&export=orders'}>Izvoz pripadajočih naročil CSV</a></div></section>}
        <div className="mt-5 flex flex-wrap items-center justify-between gap-2"><input aria-label="Poišči območje" placeholder="Poišči občino ali regijo …" value={search} onChange={event => setSearch(event.target.value)} className={control + ' min-w-56'} /><div className="flex gap-2"><select aria-label="Razvrsti območja" value={sort} onChange={event => setSort(event.target.value as typeof sort)} className={control}><option value="orders">Po številu naročil</option><option value="value">Po vrednosti</option><option value="name">Po imenu</option></select><button className={control} onClick={() => downloadRows('Obmocja', ['Območje', 'Koda', 'Naročila', 'Vrednost blaga (EUR)', 'Povezani naročniki', 'Delež preslikanih naročil'], tableRows)}>CSV tabele</button></div></div>
        <div className="mt-3 max-h-80 overflow-auto"><table className="w-full text-left text-xs"><thead className="sticky top-0 bg-slate-50"><tr>{['Območje', 'Koda', 'Naročila', 'Vrednost blaga (EUR)', 'Povezani naročniki', 'Delež preslikanih'].map(label => <th key={label} scope="col" className="whitespace-nowrap px-2 py-2 font-medium text-slate-500">{label}</th>)}</tr></thead><tbody>{areas.map(area => <tr key={area.id} className={`border-t border-slate-100 ${selectedId === area.id ? 'bg-green-50' : ''}`}><td className="p-2"><button className="text-left text-blue-700 underline" onClick={() => { setSelectedId(area.id); setHoverId(''); }}>{area.name}</button></td><td className="p-2">{area.code}</td><td className="p-2">{area.orderCount}</td><td className="p-2">{eur(area.activityValue)}</td><td className="p-2">{area.distinctCustomers}</td><td className="p-2">{percent(area.mappedShare)}</td></tr>)}</tbody></table></div>
        <details className="mt-4 rounded-lg border border-slate-200 p-3 text-xs"><summary className="cursor-pointer font-medium text-slate-700">Pripis naslovov, nerazrešeni zapisi in preverjeni popravki</summary><div className="mt-3 space-y-3 text-slate-600"><p>Pokritost: {data.coverage.resolvedOrders}/{data.reconciliation.allEligibleOrders}. Neujemajoči posnetki: {data.coverage.staleAddressResolutions}; druga različica meja: {data.coverage.otherVintageOrders}. Registrski naslovi z območjem: {data.addressSource?.linked ?? 0}/{data.addressSource?.total ?? 0}; zadnji uvoz {data.addressSource?.imported_at ?? 'še ni izveden'}.</p><DataTable columns={['Naročilo', 'Stanje pripisa', 'Metoda']} rows={data.unresolved.map(record => ({ values: [record.number, record.status, record.method], href: record.href }))} /><button type="button" disabled={pending} className={control} onClick={() => void mutate(false, true)}>Nadaljuj paketni pripis (do 100 naročil)</button><p>Popravite le preverjen naslovni pripis. Razlog in prejšnja vrednost ostaneta v revizijski sledi; osveževanje ohrani ročni popravek.</p><div className="flex flex-wrap gap-2"><label className="grid gap-1">Interni ID naročila<input required inputMode="numeric" className={control} value={correctionOrder} onChange={event => setCorrectionOrder(event.target.value)} /></label><label className="grid gap-1">{level === 'municipality' ? 'Preverjena občina' : 'Preverjena regija'}<select className={control} value={correctionArea} onChange={event => setCorrectionArea(event.target.value)}><option value="">Izberite območje</option>{data.areas.filter(area => area.level === level).map(area => <option key={area.id} value={area.id}>{area.name} ({area.code})</option>)}</select></label><label className="grid flex-1 gap-1">Razlog in vir preverjanja<input required minLength={3} className={control} value={reason} onChange={event => setReason(event.target.value)} /></label></div><div className="flex gap-2"><button disabled={pending || !correctionOrder || !correctionArea || reason.trim().length < 3} className={control + ' disabled:opacity-40'} onClick={() => void mutate(false)}>Shrani preverjeni popravek</button><button disabled={pending || !correctionOrder || reason.trim().length < 3} className={control + ' disabled:opacity-40'} onClick={() => void mutate(true)}>Odstrani ročni popravek</button></div><button className={control} type="button" onClick={() => void loadAudit()}>Prikaži revizijsko sled (zadnjih 100)</button><DataTable columns={['Čas', 'Naročilo', 'Dejanje', 'Admin', 'Razlog', 'Prejšnja občina', 'Nova občina', 'Različica']} rows={auditRows.map(row => ({ values: [row.created_at, row.order_id, row.action, row.actor, row.reason, byId.get(row.previous_municipality_id ?? '')?.name ?? row.previous_municipality_id, byId.get(row.municipality_id ?? '')?.name ?? row.municipality_id, row.source_version] }))} />{operation && <p role="status">{operation}</p>}</div></details>
      </>}
      <p className="mt-4 text-[10px] leading-relaxed text-slate-400">{data.reference.metadata.attribution} · {data.reference.metadata.licence} · različica {data.reference.metadata.version} · referenca občin {data.reference.metadata.sourceUpdatedAt.municipalities}; regij {data.reference.metadata.sourceUpdatedAt.regions}. {data.reference.lastError && <span className="text-amber-800">Zadnja osvežitev: {data.reference.lastError}. Ohranjena zadnja delujoča različica.</span>}</p>
    </>}
  </article>;
}
